// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.SdkKeys
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SdkKeysGetResponse_data_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "server")]
        #pragma warning disable CS1591
        Server,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "client")]
        #pragma warning disable CS1591
        Client,
        #pragma warning restore CS1591
    }
}
