// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>Enum containing the actions that can be performed against a resource. Group operations are included.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ACLAction
    {
        [EnumMember(Value = "create")]
        #pragma warning disable CS1591
        Create,
        #pragma warning restore CS1591
        [EnumMember(Value = "delete")]
        #pragma warning disable CS1591
        Delete,
        #pragma warning restore CS1591
        [EnumMember(Value = "read")]
        #pragma warning disable CS1591
        Read,
        #pragma warning restore CS1591
        [EnumMember(Value = "update")]
        #pragma warning disable CS1591
        Update,
        #pragma warning restore CS1591
        [EnumMember(Value = "list")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
    }
}
