// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AiGatewayBudget : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alertThresholds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<double?>? AlertThresholds { get; set; }
#nullable restore
#else
        public List<double?> AlertThresholds { get; set; }
#endif
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The createdAt property</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The currentByokSpend property</summary>
        public double? CurrentByokSpend { get; set; }
        /// <summary>The currentSpend property</summary>
        public double? CurrentSpend { get; set; }
        /// <summary>The includeByokInQuota property</summary>
        public bool? IncludeByokInQuota { get; set; }
        /// <summary>The limitAmount property</summary>
        public double? LimitAmount { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The quotaEntityId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuotaEntityId { get; set; }
#nullable restore
#else
        public string QuotaEntityId { get; set; }
#endif
        /// <summary>The refreshPeriod property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetRefreshPeriod? RefreshPeriod { get; set; }
        /// <summary>The native Vercel id of the scoped entity. Team/project ids already carry their prefix, so this equals `quotaEntityId` (`team_…` / `prj_…`); for the api-key scope it is the api key id (the `api_key_id_` prefix stripped).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScopeId { get; set; }
#nullable restore
#else
        public string ScopeId { get; set; }
#endif
        /// <summary>The scopeType property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetScopeType? ScopeType { get; set; }
        /// <summary>Set when the row is inherited from the team&apos;s budget default.</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.DefaultValueSource? Source { get; set; }
        /// <summary>The updatedAt property</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudget"/> and sets the default values.
        /// </summary>
        public AiGatewayBudget()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudget"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudget CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudget();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "alertThresholds", n => { AlertThresholds = n.GetCollectionOfPrimitiveValues<double?>()?.AsList(); } },
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "currentByokSpend", n => { CurrentByokSpend = n.GetDoubleValue(); } },
                { "currentSpend", n => { CurrentSpend = n.GetDoubleValue(); } },
                { "includeByokInQuota", n => { IncludeByokInQuota = n.GetBoolValue(); } },
                { "limitAmount", n => { LimitAmount = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "quotaEntityId", n => { QuotaEntityId = n.GetStringValue(); } },
                { "refreshPeriod", n => { RefreshPeriod = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetRefreshPeriod>(); } },
                { "scopeId", n => { ScopeId = n.GetStringValue(); } },
                { "scopeType", n => { ScopeType = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetScopeType>(); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.DefaultValueSource>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteCollectionOfPrimitiveValues<double?>("alertThresholds", AlertThresholds);
            writer.WriteBoolValue("archived", Archived);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteDoubleValue("currentByokSpend", CurrentByokSpend);
            writer.WriteDoubleValue("currentSpend", CurrentSpend);
            writer.WriteBoolValue("includeByokInQuota", IncludeByokInQuota);
            writer.WriteDoubleValue("limitAmount", LimitAmount);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("quotaEntityId", QuotaEntityId);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetRefreshPeriod>("refreshPeriod", RefreshPeriod);
            writer.WriteStringValue("scopeId", ScopeId);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.AiGatewayBudgetScopeType>("scopeType", ScopeType);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.DefaultValueSource>("source", Source);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
