// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>For kind=router: how to order candidates.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiGatewayVirtualModelConfigSelector
    {
        [EnumMember(Value = "cost")]
        #pragma warning disable CS1591
        Cost,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
        [EnumMember(Value = "tps")]
        #pragma warning disable CS1591
        Tps,
        #pragma warning restore CS1591
        [EnumMember(Value = "ttft")]
        #pragma warning disable CS1591
        Ttft,
        #pragma warning restore CS1591
    }
}
