// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>Service tier for providers that support it.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AiGatewayVirtualModelConfigServiceTier
    {
        [EnumMember(Value = "fast")]
        #pragma warning disable CS1591
        Fast,
        #pragma warning restore CS1591
        [EnumMember(Value = "flex")]
        #pragma warning disable CS1591
        Flex,
        #pragma warning restore CS1591
        [EnumMember(Value = "priority")]
        #pragma warning disable CS1591
        Priority,
        #pragma warning restore CS1591
    }
}
