// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BuyCredits200ResponseOrbSubscriptionIntent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The configuration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentConfiguration? Configuration { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentConfiguration Configuration { get; set; }
#endif
        /// <summary>The ISO 8601 date-time that the intent was created.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The ID of the Orb subscription intent with the format `orbsubint_`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The Orb subscription ID this intent is associated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrbSubscriptionId { get; set; }
#nullable restore
#else
        public string OrbSubscriptionId { get; set; }
#endif
        /// <summary>The orbUpdate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentOrbUpdate? OrbUpdate { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentOrbUpdate OrbUpdate { get; set; }
#endif
        /// <summary>The owner ID for this intent (e.g., team or user ID).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>Optional purchase intent ID if this is associated with a purchase.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PurchaseIntentId { get; set; }
#nullable restore
#else
        public string PurchaseIntentId { get; set; }
#endif
        /// <summary>The status of the Orb subscription intent.</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentStatus? Status { get; set; }
        /// <summary>The ISO 8601 date-time that the intent was last updated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntent"/> and sets the default values.
        /// </summary>
        public BuyCredits200ResponseOrbSubscriptionIntent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "configuration", n => { Configuration = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentConfiguration>(global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentConfiguration.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "orbSubscriptionId", n => { OrbSubscriptionId = n.GetStringValue(); } },
                { "orbUpdate", n => { OrbUpdate = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentOrbUpdate>(global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentOrbUpdate.CreateFromDiscriminatorValue); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "purchaseIntentId", n => { PurchaseIntentId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentStatus>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentConfiguration>("configuration", Configuration);
            writer.WriteStringValue("createdAt", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("orbSubscriptionId", OrbSubscriptionId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentOrbUpdate>("orbUpdate", OrbUpdate);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteStringValue("purchaseIntentId", PurchaseIntentId);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.BuyCredits200ResponseOrbSubscriptionIntentStatus>("status", Status);
            writer.WriteStringValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
