// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CancelDeployment200ResponseServicesItemRoutePrefixSource
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "configured")]
        #pragma warning disable CS1591
        Configured,
        #pragma warning restore CS1591
        [EnumMember(Value = "generated")]
        #pragma warning disable CS1591
        Generated,
        #pragma warning restore CS1591
    }
}
