// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>GitHub App owner type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ConnectConnectorCreateDataTypeGithubOwnerType
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User1,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization1,
        #pragma warning restore CS1591
    }
}
