// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateDeployment200ResponseGitSource : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The gitUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitUrl { get; set; }
#nullable restore
#else
        public string GitUrl { get; set; }
#endif
        /// <summary>The host property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Host { get; set; }
#nullable restore
#else
        public string Host { get; set; }
#endif
        /// <summary>The org property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Org { get; set; }
#nullable restore
#else
        public string Org { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>The prId property</summary>
        public double? PrId { get; set; }
        /// <summary>The projectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceProjectId? ProjectId { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceProjectId ProjectId { get; set; }
#endif
        /// <summary>The ref property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ref { get; set; }
#nullable restore
#else
        public string Ref { get; set; }
#endif
        /// <summary>The repo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Repo { get; set; }
#nullable restore
#else
        public string Repo { get; set; }
#endif
        /// <summary>The repoId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceRepoId? RepoId { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceRepoId RepoId { get; set; }
#endif
        /// <summary>The repoPushedAt property</summary>
        public double? RepoPushedAt { get; set; }
        /// <summary>The repoUuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RepoUuid { get; set; }
#nullable restore
#else
        public string RepoUuid { get; set; }
#endif
        /// <summary>The sha property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sha { get; set; }
#nullable restore
#else
        public string Sha { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceType? Type { get; set; }
        /// <summary>The workspaceUuid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkspaceUuid { get; set; }
#nullable restore
#else
        public string WorkspaceUuid { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSource"/> and sets the default values.
        /// </summary>
        public CreateDeployment200ResponseGitSource()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "gitUrl", n => { GitUrl = n.GetStringValue(); } },
                { "host", n => { Host = n.GetStringValue(); } },
                { "org", n => { Org = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "prId", n => { PrId = n.GetDoubleValue(); } },
                { "projectId", n => { ProjectId = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceProjectId>(global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceProjectId.CreateFromDiscriminatorValue); } },
                { "ref", n => { Ref = n.GetStringValue(); } },
                { "repo", n => { Repo = n.GetStringValue(); } },
                { "repoId", n => { RepoId = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceRepoId>(global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceRepoId.CreateFromDiscriminatorValue); } },
                { "repoPushedAt", n => { RepoPushedAt = n.GetDoubleValue(); } },
                { "repoUuid", n => { RepoUuid = n.GetStringValue(); } },
                { "sha", n => { Sha = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceType>(); } },
                { "workspaceUuid", n => { WorkspaceUuid = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("gitUrl", GitUrl);
            writer.WriteStringValue("host", Host);
            writer.WriteStringValue("org", Org);
            writer.WriteStringValue("owner", Owner);
            writer.WriteDoubleValue("prId", PrId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceProjectId>("projectId", ProjectId);
            writer.WriteStringValue("ref", Ref);
            writer.WriteStringValue("repo", Repo);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceRepoId>("repoId", RepoId);
            writer.WriteDoubleValue("repoPushedAt", RepoPushedAt);
            writer.WriteStringValue("repoUuid", RepoUuid);
            writer.WriteStringValue("sha", Sha);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateDeployment200ResponseGitSourceType>("type", Type);
            writer.WriteStringValue("workspaceUuid", WorkspaceUuid);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
