// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>Must be of type `CNAME`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateRecordRequestAnyOf5Type
    {
        [EnumMember(Value = "CNAME")]
        #pragma warning disable CS1591
        Cname,
        #pragma warning restore CS1591
    }
}
