// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>Must be of type `HTTPS`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateRecordMember10_type
    {
        [EnumMember(Value = "HTTPS")]
        #pragma warning disable CS1591
        HTTPS,
        #pragma warning restore CS1591
    }
}
