// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>
    /// &quot;Restricts which deployment sources are allowed. A deployment passes if its source is in `sources`. Multiple entries are evaluated as OR. `enabled: true` with an empty `sources` list is treated as deny-all.&quot;
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateProject200_deploymentPolicy_deploymentSources : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The environments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments>? Environments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments> Environments { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The sources property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_sources?>? Sources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_sources?> Sources { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources"/> and sets the default values.
        /// </summary>
        public CreateProject200_deploymentPolicy_deploymentSources()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "environments", n => { Environments = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments>(global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "sources", n => { Sources = n.GetCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_sources>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments>("environments", Environments);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_sources>("sources", Sources);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class CreateProject200_deploymentPolicy_deploymentSources_environments : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1? CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1 CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2? CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2 CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources.CreateProject200_deploymentPolicy_deploymentSources_environments();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1 = new global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2 = new global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1 != null)
                {
                    return CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1.GetFieldDeserializers();
                }
                else if(CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2 != null)
                {
                    return CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember1>(null, CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember1);
                }
                else if(CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.CreateProject200_deploymentPolicy_deploymentSources_environmentsMember2>(null, CreateProject200DeploymentPolicyDeploymentSourcesEnvironmentsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
