// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>Current provisioning state</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateDeployment200ResponseOneOf2ManualProvisioningState
    {
        [EnumMember(Value = "COMPLETE")]
        #pragma warning disable CS1591
        Complete,
        #pragma warning restore CS1591
        [EnumMember(Value = "PENDING")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "TIMEOUT")]
        #pragma warning disable CS1591
        Timeout,
        #pragma warning restore CS1591
    }
}
