// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum FilterProjectEnvs200ResponseEnvsItemTargetOneOf2
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "development")]
        #pragma warning disable CS1591
        Development1,
        #pragma warning restore CS1591
        [EnumMember(Value = "preview")]
        #pragma warning disable CS1591
        Preview1,
        #pragma warning restore CS1591
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
    }
}
