// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class FlagsSdkKey : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Connection string for the SDK</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectionString { get; set; }
#nullable restore
#else
        public string ConnectionString { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The deletedAt property</summary>
        public double? DeletedAt { get; set; }
        /// <summary>The environment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Environment { get; set; }
#nullable restore
#else
        public string Environment { get; set; }
#endif
        /// <summary>The hashKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HashKey { get; set; }
#nullable restore
#else
        public string HashKey { get; set; }
#endif
        /// <summary>Cleartext value of the SDK key</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? KeyValue { get; set; }
#nullable restore
#else
        public string KeyValue { get; set; }
#endif
        /// <summary>The label property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Label { get; set; }
#nullable restore
#else
        public string Label { get; set; }
#endif
        /// <summary>Partially-masked representation of the SDK key value, safe to display in UIs. The value is the `vf_&lt;type&gt;_` prefix followed by the first 3 characters of the secret portion and a fixed 8-character `*` mask (e.g. `vf_server_abc********`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PartialKeyValue { get; set; }
#nullable restore
#else
        public string PartialKeyValue { get; set; }
#endif
        /// <summary>The projectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>Cleartext value of the Edge Config token</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TokenValue { get; set; }
#nullable restore
#else
        public string TokenValue { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey_type? Type { get; set; }
        /// <summary>The updatedAt property</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey"/> and sets the default values.
        /// </summary>
        public FlagsSdkKey()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "connectionString", n => { ConnectionString = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "deletedAt", n => { DeletedAt = n.GetDoubleValue(); } },
                { "environment", n => { Environment = n.GetStringValue(); } },
                { "hashKey", n => { HashKey = n.GetStringValue(); } },
                { "keyValue", n => { KeyValue = n.GetStringValue(); } },
                { "label", n => { Label = n.GetStringValue(); } },
                { "partialKeyValue", n => { PartialKeyValue = n.GetStringValue(); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "tokenValue", n => { TokenValue = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey_type>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("connectionString", ConnectionString);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteDoubleValue("deletedAt", DeletedAt);
            writer.WriteStringValue("environment", Environment);
            writer.WriteStringValue("hashKey", HashKey);
            writer.WriteStringValue("keyValue", KeyValue);
            writer.WriteStringValue("label", Label);
            writer.WriteStringValue("partialKeyValue", PartialKeyValue);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteStringValue("tokenValue", TokenValue);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.FlagsSdkKey_type>("type", Type);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
