// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetAllLogDrains200ResponseOneOf2DrainsOneOf1ItemFilterV2FilterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "basic")]
        #pragma warning disable CS1591
        Basic,
        #pragma warning restore CS1591
        [EnumMember(Value = "odata")]
        #pragma warning disable CS1591
        Odata,
        #pragma warning restore CS1591
    }
}
