// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>
    /// Check run backed by a project-level `check` definition.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GetDeploymentCheckRun200ResponseOneOf1 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blocks property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Blocks? Blocks { get; set; }
        /// <summary>The checkId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckId { get; set; }
#nullable restore
#else
        public string CheckId { get; set; }
#endif
        /// <summary>The completedAt property</summary>
        public double? CompletedAt { get; set; }
        /// <summary>The conclusion property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Conclusion? Conclusion { get; set; }
        /// <summary>The conclusionText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConclusionText { get; set; }
#nullable restore
#else
        public string ConclusionText { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The deploymentId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentId { get; set; }
#nullable restore
#else
        public string DeploymentId { get; set; }
#endif
        /// <summary>The externalId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>The externalUrl property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalUrl { get; set; }
#nullable restore
#else
        public string ExternalUrl { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The output property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Output? Output { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Output Output { get; set; }
#endif
        /// <summary>The ownerId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The projectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The requires property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Requires? Requires { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Source? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Source Source { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Status? Status { get; set; }
        /// <summary>The targets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Targets { get; set; }
#nullable restore
#else
        public List<string> Targets { get; set; }
#endif
        /// <summary>The timeout property</summary>
        public double? Timeout { get; set; }
        /// <summary>The updatedAt property</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1"/> and sets the default values.
        /// </summary>
        public GetDeploymentCheckRun200ResponseOneOf1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocks", n => { Blocks = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Blocks>(); } },
                { "checkId", n => { CheckId = n.GetStringValue(); } },
                { "completedAt", n => { CompletedAt = n.GetDoubleValue(); } },
                { "conclusion", n => { Conclusion = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Conclusion>(); } },
                { "conclusionText", n => { ConclusionText = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "deploymentId", n => { DeploymentId = n.GetStringValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "externalUrl", n => { ExternalUrl = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "output", n => { Output = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Output>(global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Output.CreateFromDiscriminatorValue); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "requires", n => { Requires = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Requires>(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Source>(global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Source.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Status>(); } },
                { "targets", n => { Targets = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "timeout", n => { Timeout = n.GetDoubleValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Blocks>("blocks", Blocks);
            writer.WriteStringValue("checkId", CheckId);
            writer.WriteDoubleValue("completedAt", CompletedAt);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Conclusion>("conclusion", Conclusion);
            writer.WriteStringValue("conclusionText", ConclusionText);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteStringValue("deploymentId", DeploymentId);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("externalUrl", ExternalUrl);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Output>("output", Output);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Requires>("requires", Requires);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Source>("source", Source);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetDeploymentCheckRun200ResponseOneOf1Status>("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("targets", Targets);
            writer.WriteDoubleValue("timeout", Timeout);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
