// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetIntegrationLogDrains200ResponseResponseJsonItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branch regexp of log drain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Branch { get; set; }
#nullable restore
#else
        public string Branch { get; set; }
#endif
        /// <summary>The oauth2 client application id that created this log drain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>The client configuration this log drain was created with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigurationId { get; set; }
#nullable restore
#else
        public string ConfigurationId { get; set; }
#endif
        /// <summary>A timestamp that tells you when the log drain was created</summary>
        public double? CreatedAt { get; set; }
        /// <summary>Whether the log drain was created by an integration or by a user</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemCreatedFrom? CreatedFrom { get; set; }
        /// <summary>The delivery log format</summary>
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemDeliveryFormat? DeliveryFormat { get; set; }
        /// <summary>The environment of log drain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemEnvironmentsItem?>? Environments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemEnvironmentsItem?> Environments { get; set; }
#endif
        /// <summary>The headers to send with the request</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemHeaders? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemHeaders Headers { get; set; }
#endif
        /// <summary>The unique identifier of the log drain. Always prefixed with `ld_`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name of the log drain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The identifier of the team or user whose events will trigger the log drain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerId { get; set; }
#nullable restore
#else
        public string OwnerId { get; set; }
#endif
        /// <summary>The projectId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The identifier of the projects this log drain is associated with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ProjectIds { get; set; }
#nullable restore
#else
        public List<string> ProjectIds { get; set; }
#endif
        /// <summary>The sampling rate of log drain</summary>
        public double? SamplingRate { get; set; }
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSource? Source { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSource Source { get; set; }
#endif
        /// <summary>The sources from which logs are currently being delivered to this log drain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSourcesItem?>? Sources { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSourcesItem?> Sources { get; set; }
#endif
        /// <summary>The URL to call when logs are generated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseResponseJsonItem"/> and sets the default values.
        /// </summary>
        public GetIntegrationLogDrains200ResponseResponseJsonItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseResponseJsonItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseResponseJsonItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseResponseJsonItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "branch", n => { Branch = n.GetStringValue(); } },
                { "clientId", n => { ClientId = n.GetStringValue(); } },
                { "configurationId", n => { ConfigurationId = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "createdFrom", n => { CreatedFrom = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemCreatedFrom>(); } },
                { "deliveryFormat", n => { DeliveryFormat = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemDeliveryFormat>(); } },
                { "environments", n => { Environments = n.GetCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemEnvironmentsItem>()?.AsList(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemHeaders>(global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemHeaders.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "ownerId", n => { OwnerId = n.GetStringValue(); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "projectIds", n => { ProjectIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "samplingRate", n => { SamplingRate = n.GetDoubleValue(); } },
                { "source", n => { Source = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSource>(global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSource.CreateFromDiscriminatorValue); } },
                { "sources", n => { Sources = n.GetCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSourcesItem>()?.AsList(); } },
                { "url", n => { Url = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("branch", Branch);
            writer.WriteStringValue("clientId", ClientId);
            writer.WriteStringValue("configurationId", ConfigurationId);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemCreatedFrom>("createdFrom", CreatedFrom);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemDeliveryFormat>("deliveryFormat", DeliveryFormat);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemEnvironmentsItem>("environments", Environments);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemHeaders>("headers", Headers);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("ownerId", OwnerId);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteCollectionOfPrimitiveValues<string>("projectIds", ProjectIds);
            writer.WriteDoubleValue("samplingRate", SamplingRate);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSource>("source", Source);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Vercel.OpenApiClient.Models.GetIntegrationLogDrains200ResponseItemSourcesItem>("sources", Sources);
            writer.WriteStringValue("url", Url);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
