// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>&quot;Customer-configurable deployment sources. Every deploy classifies to exactly one. JSON schema in `packages/deployment-policy/schemas/body.ts` enumerates exactly these values. - `&apos;git&apos;` — git provider webhook. - `&apos;cli&apos;` — Vercel CLI (legacy classic-token CLI and SIWV CLI both). - `&apos;rest-api&apos;` — direct user/team-token REST upload. Does NOT cover deploy hooks, Marketplace integrations, or first-party app tokens. - `&apos;deploy-hook&apos;` — project deploy-hook URL. The URL is the credential. - `&apos;integration&apos;` — third-party Marketplace actor: Marketplace integration token, user-delegated OAuth from a Marketplace app, or an unrecognized third-party Vercel App. First-party Vercel Apps are never `&apos;integration&apos;`. - `&apos;v0&apos;` — the v0 product surface (entitlement-gated). v0 deploys through the CLI under the hood, but classifies as its own source so a team can allow or deny v0 independently of `&apos;cli&apos;`. First-party Vercel apps (Toolbar, etc.) classify as `&apos;first-party&apos;` — see `ClassifiedSource` in `./checks`. They&apos;re not in this union because they aren&apos;t customer-configurable; they bypass `checkDeploymentSources` entirely. v0 is intentionally NOT among them: like the CLI, it&apos;s a real product surface and is policy-controllable.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetProjects200ResponseOneOf3ProjectsItemDeploymentPolicyDeploymentSourcesItemSourcesItem
    {
        [EnumMember(Value = "cli")]
        #pragma warning disable CS1591
        Cli,
        #pragma warning restore CS1591
        [EnumMember(Value = "deploy-hook")]
        #pragma warning disable CS1591
        DeployHook,
        #pragma warning restore CS1591
        [EnumMember(Value = "git")]
        #pragma warning disable CS1591
        Git,
        #pragma warning restore CS1591
        [EnumMember(Value = "integration")]
        #pragma warning disable CS1591
        Integration,
        #pragma warning restore CS1591
        [EnumMember(Value = "rest-api")]
        #pragma warning disable CS1591
        RestApi,
        #pragma warning restore CS1591
        [EnumMember(Value = "v0")]
        #pragma warning disable CS1591
        V0,
        #pragma warning restore CS1591
    }
}
