// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetProjects200Member1_projects_alias_configuredBy
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "CNAME")]
        #pragma warning disable CS1591
        CNAME,
        #pragma warning restore CS1591
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "http")]
        #pragma warning disable CS1591
        Http,
        #pragma warning restore CS1591
        [EnumMember(Value = "dns-01")]
        #pragma warning disable CS1591
        Dns01,
        #pragma warning restore CS1591
    }
}
