// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetSecurityFirewallEventsSummary200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blockingIps property</summary>
        public double? BlockingIps { get; set; }
        /// <summary>The byAction property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByAction? ByAction { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByAction ByAction { get; set; }
#endif
        /// <summary>The byActionType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByActionType? ByActionType { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByActionType ByActionType { get; set; }
#endif
        /// <summary>The challengingIps property</summary>
        public double? ChallengingIps { get; set; }
        /// <summary>The other property</summary>
        public double? Other { get; set; }
        /// <summary>The total property</summary>
        public double? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200Response"/> and sets the default values.
        /// </summary>
        public GetSecurityFirewallEventsSummary200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blockingIps", n => { BlockingIps = n.GetDoubleValue(); } },
                { "byAction", n => { ByAction = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByAction>(global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByAction.CreateFromDiscriminatorValue); } },
                { "byActionType", n => { ByActionType = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByActionType>(global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByActionType.CreateFromDiscriminatorValue); } },
                { "challengingIps", n => { ChallengingIps = n.GetDoubleValue(); } },
                { "other", n => { Other = n.GetDoubleValue(); } },
                { "total", n => { Total = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("blockingIps", BlockingIps);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByAction>("byAction", ByAction);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.GetSecurityFirewallEventsSummary200ResponseByActionType>("byActionType", ByActionType);
            writer.WriteDoubleValue("challengingIps", ChallengingIps);
            writer.WriteDoubleValue("other", Other);
            writer.WriteDoubleValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
