// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetVercelCiTaskRunLogsLevelParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "trace")]
        #pragma warning disable CS1591
        Trace,
        #pragma warning restore CS1591
        [EnumMember(Value = "debug")]
        #pragma warning disable CS1591
        Debug,
        #pragma warning restore CS1591
        [EnumMember(Value = "command")]
        #pragma warning disable CS1591
        Command,
        #pragma warning restore CS1591
        [EnumMember(Value = "info")]
        #pragma warning disable CS1591
        Info,
        #pragma warning restore CS1591
        [EnumMember(Value = "warn")]
        #pragma warning disable CS1591
        Warn,
        #pragma warning restore CS1591
        [EnumMember(Value = "error")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
        [EnumMember(Value = "systemError")]
        #pragma warning disable CS1591
        SystemError,
        #pragma warning restore CS1591
        [EnumMember(Value = "fatal")]
        #pragma warning disable CS1591
        Fatal,
        #pragma warning restore CS1591
    }
}
