// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum InternalServerErrorCode
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "internal_server_error")]
        #pragma warning disable CS1591
        InternalServerError,
        #pragma warning restore CS1591
    }
}
