// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NotAuthorizedForScope_code
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "not_authorized_for_scope")]
        #pragma warning disable CS1591
        Not_authorized_for_scope,
        #pragma warning restore CS1591
    }
}
