// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>The time period to keep production deployments for</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PatchTeamRequestDefaultExpirationSettingsExpirationProduction
    {
        [EnumMember(Value = "3y")]
        #pragma warning disable CS1591
        Value3Y,
        #pragma warning restore CS1591
        [EnumMember(Value = "2y")]
        #pragma warning disable CS1591
        Value2Y,
        #pragma warning restore CS1591
        [EnumMember(Value = "1y")]
        #pragma warning disable CS1591
        Value1Y,
        #pragma warning restore CS1591
        [EnumMember(Value = "6m")]
        #pragma warning disable CS1591
        Value6M,
        #pragma warning restore CS1591
        [EnumMember(Value = "3m")]
        #pragma warning disable CS1591
        Value3M,
        #pragma warning restore CS1591
        [EnumMember(Value = "2m")]
        #pragma warning disable CS1591
        Value2M,
        #pragma warning restore CS1591
        [EnumMember(Value = "1m")]
        #pragma warning disable CS1591
        Value1M,
        #pragma warning restore CS1591
        [EnumMember(Value = "2w")]
        #pragma warning disable CS1591
        Value2W,
        #pragma warning restore CS1591
        [EnumMember(Value = "1w")]
        #pragma warning disable CS1591
        Value1W,
        #pragma warning restore CS1591
        [EnumMember(Value = "1d")]
        #pragma warning disable CS1591
        Value1D,
        #pragma warning restore CS1591
        [EnumMember(Value = "unlimited")]
        #pragma warning disable CS1591
        Unlimited,
        #pragma warning restore CS1591
    }
}
