// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>The network policy mode. - &apos;allow-all&apos;: All traffic is allowed. - &apos;deny-all&apos;: All traffic is blocked. - &apos;custom&apos;: Traffic is controlled by explicit allow/deny rules.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SandboxNetworkPolicy_mode
    {
        [EnumMember(Value = "allow-all")]
        #pragma warning disable CS1591
        AllowAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "deny-all")]
        #pragma warning disable CS1591
        DenyAll,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
    }
}
