// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SubmitBillingDataRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Billing data (interim invoicing data).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestBilling? Billing { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestBilling Billing { get; set; }
#endif
        /// <summary>End of Day, the UTC datetime for when the end of the billing/usage day is in UTC time. This tells us which day the usage data is for, and also allows for your &quot;end of day&quot; to be different from UTC 00:00:00. eod must be within the period dates, and cannot be older than 24h earlier from our server&apos;s current time.</summary>
        public DateTimeOffset? Eod { get; set; }
        /// <summary>Period for the billing cycle. The period end date cannot be older than 24 hours earlier than our current server&apos;s time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestPeriod? Period { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestPeriod Period { get; set; }
#endif
        /// <summary>Server time of your integration, used to determine the most recent data for race conditions &amp; updates. Only the latest usage data for a given day, week, and month will be kept.</summary>
        public DateTimeOffset? Timestamp { get; set; }
        /// <summary>The usage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestUsageItem>? Usage { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestUsageItem> Usage { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billing", n => { Billing = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestBilling>(global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestBilling.CreateFromDiscriminatorValue); } },
                { "eod", n => { Eod = n.GetDateTimeOffsetValue(); } },
                { "period", n => { Period = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestPeriod>(global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestPeriod.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetDateTimeOffsetValue(); } },
                { "usage", n => { Usage = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestUsageItem>(global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestUsageItem.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestBilling>("billing", Billing);
            writer.WriteDateTimeOffsetValue("eod", Eod);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestPeriod>("period", Period);
            writer.WriteDateTimeOffsetValue("timestamp", Timestamp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.Models.SubmitBillingDataRequestUsageItem>("usage", Usage);
        }
    }
}
#pragma warning restore CS0618
