// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.Models.Segment"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpdateFlagSegment200Response : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.Segment"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.Segment? Segment { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.Segment Segment { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1? UpdateFlagSegment200ResponseOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1 UpdateFlagSegment200ResponseOneOf1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200Response();
            if("Segment".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.Segment = new global::Soenneker.Vercel.OpenApiClient.Models.Segment();
            }
            else if("UpdateFlagSegment200ResponseOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UpdateFlagSegment200ResponseOneOf1 = new global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(Segment != null)
            {
                return Segment.GetFieldDeserializers();
            }
            else if(UpdateFlagSegment200ResponseOneOf1 != null)
            {
                return UpdateFlagSegment200ResponseOneOf1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(Segment != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.Segment>(null, Segment);
            }
            else if(UpdateFlagSegment200ResponseOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UpdateFlagSegment200ResponseOneOf1>(null, UpdateFlagSegment200ResponseOneOf1);
            }
        }
    }
}
#pragma warning restore CS0618
