// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserEvent_payloadMember115_newOwner_resourceConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The awsAccountIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AwsAccountIds { get; set; }
#nullable restore
#else
        public List<string> AwsAccountIds { get; set; }
#endif
        /// <summary>The awsAccountType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AwsAccountType { get; set; }
#nullable restore
#else
        public string AwsAccountType { get; set; }
#endif
        /// <summary>The blobStores property</summary>
        public double? BlobStores { get; set; }
        /// <summary>The buildEntitlements property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildEntitlements? BuildEntitlements { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildEntitlements BuildEntitlements { get; set; }
#endif
        /// <summary>The buildMachine property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildMachine? BuildMachine { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildMachine BuildMachine { get; set; }
#endif
        /// <summary>The buildQueue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildQueue? BuildQueue { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildQueue BuildQueue { get; set; }
#endif
        /// <summary>The bulkRedirectsFreeLimitOverride property</summary>
        public double? BulkRedirectsFreeLimitOverride { get; set; }
        /// <summary>The cfZoneName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CfZoneName { get; set; }
#nullable restore
#else
        public string CfZoneName { get; set; }
#endif
        /// <summary>The concurrentBuilds property</summary>
        public double? ConcurrentBuilds { get; set; }
        /// <summary>The cronJobsPerProject property</summary>
        public double? CronJobsPerProject { get; set; }
        /// <summary>The customEnvironmentsPerProject property</summary>
        public double? CustomEnvironmentsPerProject { get; set; }
        /// <summary>The edgeConfigs property</summary>
        public double? EdgeConfigs { get; set; }
        /// <summary>The edgeConfigSize property</summary>
        public double? EdgeConfigSize { get; set; }
        /// <summary>The edgeFunctionExecutionTimeoutMs property</summary>
        public double? EdgeFunctionExecutionTimeoutMs { get; set; }
        /// <summary>The edgeFunctionMaxSizeBytes property</summary>
        public double? EdgeFunctionMaxSizeBytes { get; set; }
        /// <summary>The elasticConcurrencyEnabled property</summary>
        public bool? ElasticConcurrencyEnabled { get; set; }
        /// <summary>The flagsExplorerOverridesThreshold property</summary>
        public double? FlagsExplorerOverridesThreshold { get; set; }
        /// <summary>The flagsExplorerUnlimitedOverrides property</summary>
        public bool? FlagsExplorerUnlimitedOverrides { get; set; }
        /// <summary>The imageOptimizationType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageOptimizationType { get; set; }
#nullable restore
#else
        public string ImageOptimizationType { get; set; }
#endif
        /// <summary>The integrationStores property</summary>
        public double? IntegrationStores { get; set; }
        /// <summary>The kvDatabases property</summary>
        public double? KvDatabases { get; set; }
        /// <summary>The microfrontendGroupsPerTeam property</summary>
        public double? MicrofrontendGroupsPerTeam { get; set; }
        /// <summary>The microfrontendProjectsPerGroup property</summary>
        public double? MicrofrontendProjectsPerGroup { get; set; }
        /// <summary>The nodeType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeType { get; set; }
#nullable restore
#else
        public string NodeType { get; set; }
#endif
        /// <summary>The postgresDatabases property</summary>
        public double? PostgresDatabases { get; set; }
        /// <summary>The security property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_security? Security { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_security Security { get; set; }
#endif
        /// <summary>The serverlessFunctionMaxMemorySize property</summary>
        public double? ServerlessFunctionMaxMemorySize { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig"/> and sets the default values.
        /// </summary>
        public UserEvent_payloadMember115_newOwner_resourceConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "awsAccountIds", n => { AwsAccountIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "awsAccountType", n => { AwsAccountType = n.GetStringValue(); } },
                { "blobStores", n => { BlobStores = n.GetDoubleValue(); } },
                { "buildEntitlements", n => { BuildEntitlements = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildEntitlements>(global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildEntitlements.CreateFromDiscriminatorValue); } },
                { "buildMachine", n => { BuildMachine = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildMachine>(global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildMachine.CreateFromDiscriminatorValue); } },
                { "buildQueue", n => { BuildQueue = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildQueue>(global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildQueue.CreateFromDiscriminatorValue); } },
                { "bulkRedirectsFreeLimitOverride", n => { BulkRedirectsFreeLimitOverride = n.GetDoubleValue(); } },
                { "cfZoneName", n => { CfZoneName = n.GetStringValue(); } },
                { "concurrentBuilds", n => { ConcurrentBuilds = n.GetDoubleValue(); } },
                { "cronJobsPerProject", n => { CronJobsPerProject = n.GetDoubleValue(); } },
                { "customEnvironmentsPerProject", n => { CustomEnvironmentsPerProject = n.GetDoubleValue(); } },
                { "edgeConfigSize", n => { EdgeConfigSize = n.GetDoubleValue(); } },
                { "edgeConfigs", n => { EdgeConfigs = n.GetDoubleValue(); } },
                { "edgeFunctionExecutionTimeoutMs", n => { EdgeFunctionExecutionTimeoutMs = n.GetDoubleValue(); } },
                { "edgeFunctionMaxSizeBytes", n => { EdgeFunctionMaxSizeBytes = n.GetDoubleValue(); } },
                { "elasticConcurrencyEnabled", n => { ElasticConcurrencyEnabled = n.GetBoolValue(); } },
                { "flagsExplorerOverridesThreshold", n => { FlagsExplorerOverridesThreshold = n.GetDoubleValue(); } },
                { "flagsExplorerUnlimitedOverrides", n => { FlagsExplorerUnlimitedOverrides = n.GetBoolValue(); } },
                { "imageOptimizationType", n => { ImageOptimizationType = n.GetStringValue(); } },
                { "integrationStores", n => { IntegrationStores = n.GetDoubleValue(); } },
                { "kvDatabases", n => { KvDatabases = n.GetDoubleValue(); } },
                { "microfrontendGroupsPerTeam", n => { MicrofrontendGroupsPerTeam = n.GetDoubleValue(); } },
                { "microfrontendProjectsPerGroup", n => { MicrofrontendProjectsPerGroup = n.GetDoubleValue(); } },
                { "nodeType", n => { NodeType = n.GetStringValue(); } },
                { "postgresDatabases", n => { PostgresDatabases = n.GetDoubleValue(); } },
                { "security", n => { Security = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_security>(global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_security.CreateFromDiscriminatorValue); } },
                { "serverlessFunctionMaxMemorySize", n => { ServerlessFunctionMaxMemorySize = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("awsAccountIds", AwsAccountIds);
            writer.WriteStringValue("awsAccountType", AwsAccountType);
            writer.WriteDoubleValue("blobStores", BlobStores);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildEntitlements>("buildEntitlements", BuildEntitlements);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildMachine>("buildMachine", BuildMachine);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_buildQueue>("buildQueue", BuildQueue);
            writer.WriteDoubleValue("bulkRedirectsFreeLimitOverride", BulkRedirectsFreeLimitOverride);
            writer.WriteStringValue("cfZoneName", CfZoneName);
            writer.WriteDoubleValue("concurrentBuilds", ConcurrentBuilds);
            writer.WriteDoubleValue("cronJobsPerProject", CronJobsPerProject);
            writer.WriteDoubleValue("customEnvironmentsPerProject", CustomEnvironmentsPerProject);
            writer.WriteDoubleValue("edgeConfigs", EdgeConfigs);
            writer.WriteDoubleValue("edgeConfigSize", EdgeConfigSize);
            writer.WriteDoubleValue("edgeFunctionExecutionTimeoutMs", EdgeFunctionExecutionTimeoutMs);
            writer.WriteDoubleValue("edgeFunctionMaxSizeBytes", EdgeFunctionMaxSizeBytes);
            writer.WriteBoolValue("elasticConcurrencyEnabled", ElasticConcurrencyEnabled);
            writer.WriteDoubleValue("flagsExplorerOverridesThreshold", FlagsExplorerOverridesThreshold);
            writer.WriteBoolValue("flagsExplorerUnlimitedOverrides", FlagsExplorerUnlimitedOverrides);
            writer.WriteStringValue("imageOptimizationType", ImageOptimizationType);
            writer.WriteDoubleValue("integrationStores", IntegrationStores);
            writer.WriteDoubleValue("kvDatabases", KvDatabases);
            writer.WriteDoubleValue("microfrontendGroupsPerTeam", MicrofrontendGroupsPerTeam);
            writer.WriteDoubleValue("microfrontendProjectsPerGroup", MicrofrontendProjectsPerGroup);
            writer.WriteStringValue("nodeType", NodeType);
            writer.WriteDoubleValue("postgresDatabases", PostgresDatabases);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEvent_payloadMember115_newOwner_resourceConfig_security>("security", Security);
            writer.WriteDoubleValue("serverlessFunctionMaxMemorySize", ServerlessFunctionMaxMemorySize);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
