// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserEvent_payloadMember122_newOwner_featureBlocks_redisMember1_blockReason
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "limits_exceeded")]
        #pragma warning disable CS1591
        Limits_exceeded,
        #pragma warning restore CS1591
    }
}
