// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserEventPayloadOneOf116Job : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1? UserEventPayloadOneOf116JobOneOf1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1 UserEventPayloadOneOf116JobOneOf1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10? UserEventPayloadOneOf116JobOneOf10 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10 UserEventPayloadOneOf116JobOneOf10 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2? UserEventPayloadOneOf116JobOneOf2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2 UserEventPayloadOneOf116JobOneOf2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3? UserEventPayloadOneOf116JobOneOf3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3 UserEventPayloadOneOf116JobOneOf3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4? UserEventPayloadOneOf116JobOneOf4 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4 UserEventPayloadOneOf116JobOneOf4 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5? UserEventPayloadOneOf116JobOneOf5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5 UserEventPayloadOneOf116JobOneOf5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6? UserEventPayloadOneOf116JobOneOf6 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6 UserEventPayloadOneOf116JobOneOf6 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7? UserEventPayloadOneOf116JobOneOf7 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7 UserEventPayloadOneOf116JobOneOf7 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8? UserEventPayloadOneOf116JobOneOf8 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8 UserEventPayloadOneOf116JobOneOf8 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9? UserEventPayloadOneOf116JobOneOf9 { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9 UserEventPayloadOneOf116JobOneOf9 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116Job"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116Job CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116Job();
            if("UserEventPayloadOneOf116JobOneOf1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf1 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1();
            }
            else if("UserEventPayloadOneOf116JobOneOf10".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf10 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10();
            }
            else if("UserEventPayloadOneOf116JobOneOf2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf2 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2();
            }
            else if("UserEventPayloadOneOf116JobOneOf3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf3 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3();
            }
            else if("UserEventPayloadOneOf116JobOneOf4".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf4 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4();
            }
            else if("UserEventPayloadOneOf116JobOneOf5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf5 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5();
            }
            else if("UserEventPayloadOneOf116JobOneOf6".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf6 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6();
            }
            else if("UserEventPayloadOneOf116JobOneOf7".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf7 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7();
            }
            else if("UserEventPayloadOneOf116JobOneOf8".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf8 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8();
            }
            else if("UserEventPayloadOneOf116JobOneOf9".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.UserEventPayloadOneOf116JobOneOf9 = new global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(UserEventPayloadOneOf116JobOneOf1 != null)
            {
                return UserEventPayloadOneOf116JobOneOf1.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf10 != null)
            {
                return UserEventPayloadOneOf116JobOneOf10.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf2 != null)
            {
                return UserEventPayloadOneOf116JobOneOf2.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf3 != null)
            {
                return UserEventPayloadOneOf116JobOneOf3.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf4 != null)
            {
                return UserEventPayloadOneOf116JobOneOf4.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf5 != null)
            {
                return UserEventPayloadOneOf116JobOneOf5.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf6 != null)
            {
                return UserEventPayloadOneOf116JobOneOf6.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf7 != null)
            {
                return UserEventPayloadOneOf116JobOneOf7.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf8 != null)
            {
                return UserEventPayloadOneOf116JobOneOf8.GetFieldDeserializers();
            }
            else if(UserEventPayloadOneOf116JobOneOf9 != null)
            {
                return UserEventPayloadOneOf116JobOneOf9.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(UserEventPayloadOneOf116JobOneOf1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf1>(null, UserEventPayloadOneOf116JobOneOf1);
            }
            else if(UserEventPayloadOneOf116JobOneOf10 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf10>(null, UserEventPayloadOneOf116JobOneOf10);
            }
            else if(UserEventPayloadOneOf116JobOneOf2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf2>(null, UserEventPayloadOneOf116JobOneOf2);
            }
            else if(UserEventPayloadOneOf116JobOneOf3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf3>(null, UserEventPayloadOneOf116JobOneOf3);
            }
            else if(UserEventPayloadOneOf116JobOneOf4 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf4>(null, UserEventPayloadOneOf116JobOneOf4);
            }
            else if(UserEventPayloadOneOf116JobOneOf5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf5>(null, UserEventPayloadOneOf116JobOneOf5);
            }
            else if(UserEventPayloadOneOf116JobOneOf6 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf6>(null, UserEventPayloadOneOf116JobOneOf6);
            }
            else if(UserEventPayloadOneOf116JobOneOf7 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf7>(null, UserEventPayloadOneOf116JobOneOf7);
            }
            else if(UserEventPayloadOneOf116JobOneOf8 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf8>(null, UserEventPayloadOneOf116JobOneOf8);
            }
            else if(UserEventPayloadOneOf116JobOneOf9 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.UserEventPayloadOneOf116JobOneOf9>(null, UserEventPayloadOneOf116JobOneOf9);
            }
        }
    }
}
#pragma warning restore CS0618
