// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserEvent_payloadMember70_jobMember4_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "push")]
        #pragma warning disable CS1591
        Push,
        #pragma warning restore CS1591
    }
}
