// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V4.Aliases.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithIdOrAliasGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alias name, it could be a `.vercel.app` subdomain or a custom domain</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The date when the alias was created</summary>
        public DateTimeOffset? Created { get; set; }
        /// <summary>The date when the alias was created in milliseconds since the UNIX epoch</summary>
        public double? CreatedAt { get; set; }
        /// <summary>Information of the user who created the alias</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_creator? Creator { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_creator Creator { get; set; }
#endif
        /// <summary>The date when the alias was deleted in milliseconds since the UNIX epoch</summary>
        public double? DeletedAt { get; set; }
        /// <summary>A map with the deployment ID, URL and metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_deployment? Deployment { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_deployment Deployment { get; set; }
#endif
        /// <summary>The deployment ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeploymentId { get; set; }
#nullable restore
#else
        public string DeploymentId { get; set; }
#endif
        /// <summary>The microfrontends for the alias including the routing configuration</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_microfrontends? Microfrontends { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_microfrontends Microfrontends { get; set; }
#endif
        /// <summary>The unique identifier of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProjectId { get; set; }
#nullable restore
#else
        public string ProjectId { get; set; }
#endif
        /// <summary>The protection bypass for the alias</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_protectionBypass? ProtectionBypass { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_protectionBypass ProtectionBypass { get; set; }
#endif
        /// <summary>Target destination domain for redirect when the alias is a redirect</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Redirect { get; set; }
#nullable restore
#else
        public string Redirect { get; set; }
#endif
        /// <summary>Status code to be used on redirect</summary>
        public double? RedirectStatusCode { get; set; }
        /// <summary>The unique identifier of the alias</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uid { get; set; }
#nullable restore
#else
        public string Uid { get; set; }
#endif
        /// <summary>The date when the alias was updated in milliseconds since the UNIX epoch</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse"/> and sets the default values.
        /// </summary>
        public WithIdOrAliasGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "created", n => { Created = n.GetDateTimeOffsetValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_creator>(global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_creator.CreateFromDiscriminatorValue); } },
                { "deletedAt", n => { DeletedAt = n.GetDoubleValue(); } },
                { "deployment", n => { Deployment = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_deployment>(global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_deployment.CreateFromDiscriminatorValue); } },
                { "deploymentId", n => { DeploymentId = n.GetStringValue(); } },
                { "microfrontends", n => { Microfrontends = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_microfrontends>(global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_microfrontends.CreateFromDiscriminatorValue); } },
                { "projectId", n => { ProjectId = n.GetStringValue(); } },
                { "protectionBypass", n => { ProtectionBypass = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_protectionBypass>(global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_protectionBypass.CreateFromDiscriminatorValue); } },
                { "redirect", n => { Redirect = n.GetStringValue(); } },
                { "redirectStatusCode", n => { RedirectStatusCode = n.GetDoubleValue(); } },
                { "uid", n => { Uid = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteDateTimeOffsetValue("created", Created);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_creator>("creator", Creator);
            writer.WriteDoubleValue("deletedAt", DeletedAt);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_deployment>("deployment", Deployment);
            writer.WriteStringValue("deploymentId", DeploymentId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_microfrontends>("microfrontends", Microfrontends);
            writer.WriteStringValue("projectId", ProjectId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V4.Aliases.Item.WithIdOrAliasGetResponse_protectionBypass>("protectionBypass", ProtectionBypass);
            writer.WriteStringValue("redirect", Redirect);
            writer.WriteDoubleValue("redirectStatusCode", RedirectStatusCode);
            writer.WriteStringValue("uid", Uid);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
