// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V11.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectsPostResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The abuse property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_abuse? Abuse { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_abuse Abuse { get; set; }
#endif
        /// <summary>The accountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountId { get; set; }
#nullable restore
#else
        public string AccountId { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The analytics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_analytics? Analytics { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_analytics Analytics { get; set; }
#endif
        /// <summary>The appliedCve55182Migration property</summary>
        public bool? AppliedCve55182Migration { get; set; }
        /// <summary>The autoAssignCustomDomains property</summary>
        public bool? AutoAssignCustomDomains { get; set; }
        /// <summary>The autoAssignCustomDomainsUpdatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AutoAssignCustomDomainsUpdatedBy { get; set; }
#nullable restore
#else
        public string AutoAssignCustomDomainsUpdatedBy { get; set; }
#endif
        /// <summary>The autoExposeSystemEnvs property</summary>
        public bool? AutoExposeSystemEnvs { get; set; }
        /// <summary>The buildCommand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuildCommand { get; set; }
#nullable restore
#else
        public string BuildCommand { get; set; }
#endif
        /// <summary>The commandForIgnoringBuildStep property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CommandForIgnoringBuildStep { get; set; }
#nullable restore
#else
        public string CommandForIgnoringBuildStep { get; set; }
#endif
        /// <summary>The concurrencyBucketName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConcurrencyBucketName { get; set; }
#nullable restore
#else
        public string ConcurrencyBucketName { get; set; }
#endif
        /// <summary>The connectBuildsEnabled property</summary>
        public bool? ConnectBuildsEnabled { get; set; }
        /// <summary>The connectConfigurationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConnectConfigurationId { get; set; }
#nullable restore
#else
        public string ConnectConfigurationId { get; set; }
#endif
        /// <summary>The connectConfigurations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_connectConfigurations>? ConnectConfigurations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_connectConfigurations> ConnectConfigurations { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The crons property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_crons? Crons { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_crons Crons { get; set; }
#endif
        /// <summary>The customEnvironments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_customEnvironments>? CustomEnvironments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_customEnvironments> CustomEnvironments { get; set; }
#endif
        /// <summary>The customerSupportCodeVisibility property</summary>
        public bool? CustomerSupportCodeVisibility { get; set; }
        /// <summary>The dataCache property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dataCache? DataCache { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dataCache DataCache { get; set; }
#endif
        /// <summary>The defaultResourceConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_defaultResourceConfig? DefaultResourceConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_defaultResourceConfig DefaultResourceConfig { get; set; }
#endif
        /// <summary>Retention policies for deployments. These are enforced at the project level, but we also maintain an instance of this at the team level as a default policy that gets applied to new projects.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_deploymentExpiration? DeploymentExpiration { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_deploymentExpiration DeploymentExpiration { get; set; }
#endif
        /// <summary>The devCommand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DevCommand { get; set; }
#nullable restore
#else
        public string DevCommand { get; set; }
#endif
        /// <summary>The directoryListing property</summary>
        public bool? DirectoryListing { get; set; }
        /// <summary>The dismissedToasts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dismissedToasts>? DismissedToasts { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dismissedToasts> DismissedToasts { get; set; }
#endif
        /// <summary>The enableAffectedProjectsDeployments property</summary>
        public bool? EnableAffectedProjectsDeployments { get; set; }
        /// <summary>The enableExternalRewriteCaching property</summary>
        public bool? EnableExternalRewriteCaching { get; set; }
        /// <summary>The enablePreviewFeedback property</summary>
        public bool? EnablePreviewFeedback { get; set; }
        /// <summary>The enableProductionFeedback property</summary>
        public bool? EnableProductionFeedback { get; set; }
        /// <summary>The env property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_env>? Env { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_env> Env { get; set; }
#endif
        /// <summary>The features property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_features? Features { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_features Features { get; set; }
#endif
        /// <summary>The flatRateTier property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_flatRateTier? FlatRateTier { get; set; }
        /// <summary>The framework property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_framework? Framework { get; set; }
        /// <summary>The gitComments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitComments? GitComments { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitComments GitComments { get; set; }
#endif
        /// <summary>The gitForkProtection property</summary>
        public bool? GitForkProtection { get; set; }
        /// <summary>The gitLFS property</summary>
        public bool? GitLFS { get; set; }
        /// <summary>The gitProviderOptions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitProviderOptions? GitProviderOptions { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitProviderOptions GitProviderOptions { get; set; }
#endif
        /// <summary>The hasActiveBranches property</summary>
        public bool? HasActiveBranches { get; set; }
        /// <summary>The hasDeployments property</summary>
        public bool? HasDeployments { get; set; }
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The installCommand property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InstallCommand { get; set; }
#nullable restore
#else
        public string InstallCommand { get; set; }
#endif
        /// <summary>The internalRoutes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes>? InternalRoutes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes> InternalRoutes { get; set; }
#endif
        /// <summary>The ipBuckets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ipBuckets>? IpBuckets { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ipBuckets> IpBuckets { get; set; }
#endif
        /// <summary>The jobs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_jobs? Jobs { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_jobs Jobs { get; set; }
#endif
        /// <summary>The lastAliasRequest property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastAliasRequest? LastAliasRequest { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastAliasRequest LastAliasRequest { get; set; }
#endif
        /// <summary>The lastRollbackTarget property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastRollbackTarget? LastRollbackTarget { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastRollbackTarget LastRollbackTarget { get; set; }
#endif
        /// <summary>The latestDeployments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_latestDeployments>? LatestDeployments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_latestDeployments> LatestDeployments { get; set; }
#endif
        /// <summary>The link property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link? Link { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link Link { get; set; }
#endif
        /// <summary>The live property</summary>
        public bool? Live { get; set; }
        /// <summary>The microfrontends property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends? Microfrontends { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends Microfrontends { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The nodeVersion property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_nodeVersion? NodeVersion { get; set; }
        /// <summary>The oidcTokenConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_oidcTokenConfig? OidcTokenConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_oidcTokenConfig OidcTokenConfig { get; set; }
#endif
        /// <summary>The optionsAllowlist property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_optionsAllowlist? OptionsAllowlist { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_optionsAllowlist OptionsAllowlist { get; set; }
#endif
        /// <summary>The outputDirectory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OutputDirectory { get; set; }
#nullable restore
#else
        public string OutputDirectory { get; set; }
#endif
        /// <summary>The passiveConnectConfigurationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PassiveConnectConfigurationId { get; set; }
#nullable restore
#else
        public string PassiveConnectConfigurationId { get; set; }
#endif
        /// <summary>The passwordProtection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_passwordProtection? PasswordProtection { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_passwordProtection PasswordProtection { get; set; }
#endif
        /// <summary>The paused property</summary>
        public bool? Paused { get; set; }
        /// <summary>The permissions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_permissions? Permissions { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_permissions Permissions { get; set; }
#endif
        /// <summary>The productionDeploymentsFastLane property</summary>
        public bool? ProductionDeploymentsFastLane { get; set; }
        /// <summary>The protectedSourcemaps property</summary>
        public bool? ProtectedSourcemaps { get; set; }
        /// <summary>The protectionBypass property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_protectionBypass? ProtectionBypass { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_protectionBypass ProtectionBypass { get; set; }
#endif
        /// <summary>The publicSource property</summary>
        public bool? PublicSource { get; set; }
        /// <summary>The resourceConfig property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_resourceConfig? ResourceConfig { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_resourceConfig ResourceConfig { get; set; }
#endif
        /// <summary>Description of why a project was rolled back, and by whom. Note that lastAliasRequest contains the from/to details of the rollback.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollbackDescription? RollbackDescription { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollbackDescription RollbackDescription { get; set; }
#endif
        /// <summary>Project-level rolling release configuration that defines how deployments should be gradually rolled out</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollingRelease? RollingRelease { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollingRelease RollingRelease { get; set; }
#endif
        /// <summary>The rootDirectory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RootDirectory { get; set; }
#nullable restore
#else
        public string RootDirectory { get; set; }
#endif
        /// <summary>The security property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_security? Security { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_security Security { get; set; }
#endif
        /// <summary>The serverlessFunctionZeroConfigFailover property</summary>
        public bool? ServerlessFunctionZeroConfigFailover { get; set; }
        /// <summary>The skewProtectionAllowedDomains property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SkewProtectionAllowedDomains { get; set; }
#nullable restore
#else
        public List<string> SkewProtectionAllowedDomains { get; set; }
#endif
        /// <summary>The skewProtectionBoundaryAt property</summary>
        public double? SkewProtectionBoundaryAt { get; set; }
        /// <summary>The skewProtectionMaxAge property</summary>
        public double? SkewProtectionMaxAge { get; set; }
        /// <summary>The skipGitConnectDuringLink property</summary>
        public bool? SkipGitConnectDuringLink { get; set; }
        /// <summary>The sourceFilesOutsideRootDirectory property</summary>
        public bool? SourceFilesOutsideRootDirectory { get; set; }
        /// <summary>The speedInsights property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_speedInsights? SpeedInsights { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_speedInsights SpeedInsights { get; set; }
#endif
        /// <summary>The ssoProtection property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ssoProtection? SsoProtection { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ssoProtection SsoProtection { get; set; }
#endif
        /// <summary>The staticIps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_staticIps? StaticIps { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_staticIps StaticIps { get; set; }
#endif
        /// <summary>The targets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_targets? Targets { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_targets Targets { get; set; }
#endif
        /// <summary>The tier property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tier { get; set; }
#nullable restore
#else
        public string Tier { get; set; }
#endif
        /// <summary>The tracing property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_tracing? Tracing { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_tracing Tracing { get; set; }
#endif
        /// <summary>The transferCompletedAt property</summary>
        public double? TransferCompletedAt { get; set; }
        /// <summary>The transferredFromAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransferredFromAccountId { get; set; }
#nullable restore
#else
        public string TransferredFromAccountId { get; set; }
#endif
        /// <summary>The transferStartedAt property</summary>
        public double? TransferStartedAt { get; set; }
        /// <summary>The transferToAccountId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransferToAccountId { get; set; }
#nullable restore
#else
        public string TransferToAccountId { get; set; }
#endif
        /// <summary>The trustedIps property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps? TrustedIps { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps TrustedIps { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>The usageStatus property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_usageStatus? UsageStatus { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_usageStatus UsageStatus { get; set; }
#endif
        /// <summary>The v0 property</summary>
        public bool? V0 { get; set; }
        /// <summary>The v0Created property</summary>
        public bool? V0Created { get; set; }
        /// <summary>The webAnalytics property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_webAnalytics? WebAnalytics { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_webAnalytics WebAnalytics { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse"/> and sets the default values.
        /// </summary>
        public ProjectsPostResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "abuse", n => { Abuse = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_abuse>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_abuse.CreateFromDiscriminatorValue); } },
                { "accountId", n => { AccountId = n.GetStringValue(); } },
                { "analytics", n => { Analytics = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_analytics>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_analytics.CreateFromDiscriminatorValue); } },
                { "appliedCve55182Migration", n => { AppliedCve55182Migration = n.GetBoolValue(); } },
                { "autoAssignCustomDomains", n => { AutoAssignCustomDomains = n.GetBoolValue(); } },
                { "autoAssignCustomDomainsUpdatedBy", n => { AutoAssignCustomDomainsUpdatedBy = n.GetStringValue(); } },
                { "autoExposeSystemEnvs", n => { AutoExposeSystemEnvs = n.GetBoolValue(); } },
                { "buildCommand", n => { BuildCommand = n.GetStringValue(); } },
                { "commandForIgnoringBuildStep", n => { CommandForIgnoringBuildStep = n.GetStringValue(); } },
                { "concurrencyBucketName", n => { ConcurrencyBucketName = n.GetStringValue(); } },
                { "connectBuildsEnabled", n => { ConnectBuildsEnabled = n.GetBoolValue(); } },
                { "connectConfigurationId", n => { ConnectConfigurationId = n.GetStringValue(); } },
                { "connectConfigurations", n => { ConnectConfigurations = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_connectConfigurations>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_connectConfigurations.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "crons", n => { Crons = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_crons>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_crons.CreateFromDiscriminatorValue); } },
                { "customEnvironments", n => { CustomEnvironments = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_customEnvironments>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_customEnvironments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "customerSupportCodeVisibility", n => { CustomerSupportCodeVisibility = n.GetBoolValue(); } },
                { "dataCache", n => { DataCache = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dataCache>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dataCache.CreateFromDiscriminatorValue); } },
                { "defaultResourceConfig", n => { DefaultResourceConfig = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_defaultResourceConfig>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_defaultResourceConfig.CreateFromDiscriminatorValue); } },
                { "deploymentExpiration", n => { DeploymentExpiration = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_deploymentExpiration>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_deploymentExpiration.CreateFromDiscriminatorValue); } },
                { "devCommand", n => { DevCommand = n.GetStringValue(); } },
                { "directoryListing", n => { DirectoryListing = n.GetBoolValue(); } },
                { "dismissedToasts", n => { DismissedToasts = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dismissedToasts>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dismissedToasts.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enableAffectedProjectsDeployments", n => { EnableAffectedProjectsDeployments = n.GetBoolValue(); } },
                { "enableExternalRewriteCaching", n => { EnableExternalRewriteCaching = n.GetBoolValue(); } },
                { "enablePreviewFeedback", n => { EnablePreviewFeedback = n.GetBoolValue(); } },
                { "enableProductionFeedback", n => { EnableProductionFeedback = n.GetBoolValue(); } },
                { "env", n => { Env = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_env>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_env.CreateFromDiscriminatorValue)?.AsList(); } },
                { "features", n => { Features = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_features>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_features.CreateFromDiscriminatorValue); } },
                { "flatRateTier", n => { FlatRateTier = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_flatRateTier>(); } },
                { "framework", n => { Framework = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_framework>(); } },
                { "gitComments", n => { GitComments = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitComments>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitComments.CreateFromDiscriminatorValue); } },
                { "gitForkProtection", n => { GitForkProtection = n.GetBoolValue(); } },
                { "gitLFS", n => { GitLFS = n.GetBoolValue(); } },
                { "gitProviderOptions", n => { GitProviderOptions = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitProviderOptions>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitProviderOptions.CreateFromDiscriminatorValue); } },
                { "hasActiveBranches", n => { HasActiveBranches = n.GetBoolValue(); } },
                { "hasDeployments", n => { HasDeployments = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "installCommand", n => { InstallCommand = n.GetStringValue(); } },
                { "internalRoutes", n => { InternalRoutes = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes.CreateFromDiscriminatorValue)?.AsList(); } },
                { "ipBuckets", n => { IpBuckets = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ipBuckets>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ipBuckets.CreateFromDiscriminatorValue)?.AsList(); } },
                { "jobs", n => { Jobs = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_jobs>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_jobs.CreateFromDiscriminatorValue); } },
                { "lastAliasRequest", n => { LastAliasRequest = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastAliasRequest>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastAliasRequest.CreateFromDiscriminatorValue); } },
                { "lastRollbackTarget", n => { LastRollbackTarget = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastRollbackTarget>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastRollbackTarget.CreateFromDiscriminatorValue); } },
                { "latestDeployments", n => { LatestDeployments = n.GetCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_latestDeployments>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_latestDeployments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "link", n => { Link = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link.CreateFromDiscriminatorValue); } },
                { "live", n => { Live = n.GetBoolValue(); } },
                { "microfrontends", n => { Microfrontends = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "nodeVersion", n => { NodeVersion = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_nodeVersion>(); } },
                { "oidcTokenConfig", n => { OidcTokenConfig = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_oidcTokenConfig>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_oidcTokenConfig.CreateFromDiscriminatorValue); } },
                { "optionsAllowlist", n => { OptionsAllowlist = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_optionsAllowlist>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_optionsAllowlist.CreateFromDiscriminatorValue); } },
                { "outputDirectory", n => { OutputDirectory = n.GetStringValue(); } },
                { "passiveConnectConfigurationId", n => { PassiveConnectConfigurationId = n.GetStringValue(); } },
                { "passwordProtection", n => { PasswordProtection = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_passwordProtection>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_passwordProtection.CreateFromDiscriminatorValue); } },
                { "paused", n => { Paused = n.GetBoolValue(); } },
                { "permissions", n => { Permissions = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_permissions>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_permissions.CreateFromDiscriminatorValue); } },
                { "productionDeploymentsFastLane", n => { ProductionDeploymentsFastLane = n.GetBoolValue(); } },
                { "protectedSourcemaps", n => { ProtectedSourcemaps = n.GetBoolValue(); } },
                { "protectionBypass", n => { ProtectionBypass = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_protectionBypass>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_protectionBypass.CreateFromDiscriminatorValue); } },
                { "publicSource", n => { PublicSource = n.GetBoolValue(); } },
                { "resourceConfig", n => { ResourceConfig = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_resourceConfig>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_resourceConfig.CreateFromDiscriminatorValue); } },
                { "rollbackDescription", n => { RollbackDescription = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollbackDescription>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollbackDescription.CreateFromDiscriminatorValue); } },
                { "rollingRelease", n => { RollingRelease = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollingRelease>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollingRelease.CreateFromDiscriminatorValue); } },
                { "rootDirectory", n => { RootDirectory = n.GetStringValue(); } },
                { "security", n => { Security = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_security>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_security.CreateFromDiscriminatorValue); } },
                { "serverlessFunctionZeroConfigFailover", n => { ServerlessFunctionZeroConfigFailover = n.GetBoolValue(); } },
                { "skewProtectionAllowedDomains", n => { SkewProtectionAllowedDomains = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "skewProtectionBoundaryAt", n => { SkewProtectionBoundaryAt = n.GetDoubleValue(); } },
                { "skewProtectionMaxAge", n => { SkewProtectionMaxAge = n.GetDoubleValue(); } },
                { "skipGitConnectDuringLink", n => { SkipGitConnectDuringLink = n.GetBoolValue(); } },
                { "sourceFilesOutsideRootDirectory", n => { SourceFilesOutsideRootDirectory = n.GetBoolValue(); } },
                { "speedInsights", n => { SpeedInsights = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_speedInsights>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_speedInsights.CreateFromDiscriminatorValue); } },
                { "ssoProtection", n => { SsoProtection = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ssoProtection>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ssoProtection.CreateFromDiscriminatorValue); } },
                { "staticIps", n => { StaticIps = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_staticIps>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_staticIps.CreateFromDiscriminatorValue); } },
                { "targets", n => { Targets = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_targets>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_targets.CreateFromDiscriminatorValue); } },
                { "tier", n => { Tier = n.GetStringValue(); } },
                { "tracing", n => { Tracing = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_tracing>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_tracing.CreateFromDiscriminatorValue); } },
                { "transferCompletedAt", n => { TransferCompletedAt = n.GetDoubleValue(); } },
                { "transferStartedAt", n => { TransferStartedAt = n.GetDoubleValue(); } },
                { "transferToAccountId", n => { TransferToAccountId = n.GetStringValue(); } },
                { "transferredFromAccountId", n => { TransferredFromAccountId = n.GetStringValue(); } },
                { "trustedIps", n => { TrustedIps = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps.CreateFromDiscriminatorValue); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
                { "usageStatus", n => { UsageStatus = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_usageStatus>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_usageStatus.CreateFromDiscriminatorValue); } },
                { "v0", n => { V0 = n.GetBoolValue(); } },
                { "v0Created", n => { V0Created = n.GetBoolValue(); } },
                { "webAnalytics", n => { WebAnalytics = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_webAnalytics>(global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_webAnalytics.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_abuse>("abuse", Abuse);
            writer.WriteStringValue("accountId", AccountId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_analytics>("analytics", Analytics);
            writer.WriteBoolValue("appliedCve55182Migration", AppliedCve55182Migration);
            writer.WriteBoolValue("autoAssignCustomDomains", AutoAssignCustomDomains);
            writer.WriteStringValue("autoAssignCustomDomainsUpdatedBy", AutoAssignCustomDomainsUpdatedBy);
            writer.WriteBoolValue("autoExposeSystemEnvs", AutoExposeSystemEnvs);
            writer.WriteStringValue("buildCommand", BuildCommand);
            writer.WriteStringValue("commandForIgnoringBuildStep", CommandForIgnoringBuildStep);
            writer.WriteStringValue("concurrencyBucketName", ConcurrencyBucketName);
            writer.WriteBoolValue("connectBuildsEnabled", ConnectBuildsEnabled);
            writer.WriteStringValue("connectConfigurationId", ConnectConfigurationId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_connectConfigurations>("connectConfigurations", ConnectConfigurations);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_crons>("crons", Crons);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_customEnvironments>("customEnvironments", CustomEnvironments);
            writer.WriteBoolValue("customerSupportCodeVisibility", CustomerSupportCodeVisibility);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dataCache>("dataCache", DataCache);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_defaultResourceConfig>("defaultResourceConfig", DefaultResourceConfig);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_deploymentExpiration>("deploymentExpiration", DeploymentExpiration);
            writer.WriteStringValue("devCommand", DevCommand);
            writer.WriteBoolValue("directoryListing", DirectoryListing);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_dismissedToasts>("dismissedToasts", DismissedToasts);
            writer.WriteBoolValue("enableAffectedProjectsDeployments", EnableAffectedProjectsDeployments);
            writer.WriteBoolValue("enableExternalRewriteCaching", EnableExternalRewriteCaching);
            writer.WriteBoolValue("enablePreviewFeedback", EnablePreviewFeedback);
            writer.WriteBoolValue("enableProductionFeedback", EnableProductionFeedback);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_env>("env", Env);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_features>("features", Features);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_flatRateTier>("flatRateTier", FlatRateTier);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_framework>("framework", Framework);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitComments>("gitComments", GitComments);
            writer.WriteBoolValue("gitForkProtection", GitForkProtection);
            writer.WriteBoolValue("gitLFS", GitLFS);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_gitProviderOptions>("gitProviderOptions", GitProviderOptions);
            writer.WriteBoolValue("hasActiveBranches", HasActiveBranches);
            writer.WriteBoolValue("hasDeployments", HasDeployments);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("installCommand", InstallCommand);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes>("internalRoutes", InternalRoutes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ipBuckets>("ipBuckets", IpBuckets);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_jobs>("jobs", Jobs);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastAliasRequest>("lastAliasRequest", LastAliasRequest);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_lastRollbackTarget>("lastRollbackTarget", LastRollbackTarget);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_latestDeployments>("latestDeployments", LatestDeployments);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link>("link", Link);
            writer.WriteBoolValue("live", Live);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends>("microfrontends", Microfrontends);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_nodeVersion>("nodeVersion", NodeVersion);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_oidcTokenConfig>("oidcTokenConfig", OidcTokenConfig);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_optionsAllowlist>("optionsAllowlist", OptionsAllowlist);
            writer.WriteStringValue("outputDirectory", OutputDirectory);
            writer.WriteStringValue("passiveConnectConfigurationId", PassiveConnectConfigurationId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_passwordProtection>("passwordProtection", PasswordProtection);
            writer.WriteBoolValue("paused", Paused);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_permissions>("permissions", Permissions);
            writer.WriteBoolValue("productionDeploymentsFastLane", ProductionDeploymentsFastLane);
            writer.WriteBoolValue("protectedSourcemaps", ProtectedSourcemaps);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_protectionBypass>("protectionBypass", ProtectionBypass);
            writer.WriteBoolValue("publicSource", PublicSource);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_resourceConfig>("resourceConfig", ResourceConfig);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollbackDescription>("rollbackDescription", RollbackDescription);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_rollingRelease>("rollingRelease", RollingRelease);
            writer.WriteStringValue("rootDirectory", RootDirectory);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_security>("security", Security);
            writer.WriteBoolValue("serverlessFunctionZeroConfigFailover", ServerlessFunctionZeroConfigFailover);
            writer.WriteCollectionOfPrimitiveValues<string>("skewProtectionAllowedDomains", SkewProtectionAllowedDomains);
            writer.WriteDoubleValue("skewProtectionBoundaryAt", SkewProtectionBoundaryAt);
            writer.WriteDoubleValue("skewProtectionMaxAge", SkewProtectionMaxAge);
            writer.WriteBoolValue("skipGitConnectDuringLink", SkipGitConnectDuringLink);
            writer.WriteBoolValue("sourceFilesOutsideRootDirectory", SourceFilesOutsideRootDirectory);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_speedInsights>("speedInsights", SpeedInsights);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_ssoProtection>("ssoProtection", SsoProtection);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_staticIps>("staticIps", StaticIps);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_targets>("targets", Targets);
            writer.WriteStringValue("tier", Tier);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_tracing>("tracing", Tracing);
            writer.WriteDoubleValue("transferCompletedAt", TransferCompletedAt);
            writer.WriteStringValue("transferredFromAccountId", TransferredFromAccountId);
            writer.WriteDoubleValue("transferStartedAt", TransferStartedAt);
            writer.WriteStringValue("transferToAccountId", TransferToAccountId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps>("trustedIps", TrustedIps);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_usageStatus>("usageStatus", UsageStatus);
            writer.WriteBoolValue("v0", V0);
            writer.WriteBoolValue("v0Created", V0Created);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_webAnalytics>("webAnalytics", WebAnalytics);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsPostResponse_internalRoutes : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1? ProjectsPostResponseInternalRoutesMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1 ProjectsPostResponseInternalRoutesMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2? ProjectsPostResponseInternalRoutesMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2 ProjectsPostResponseInternalRoutesMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_internalRoutes();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseInternalRoutesMember1 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseInternalRoutesMember2 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProjectsPostResponseInternalRoutesMember1 != null)
                {
                    return ProjectsPostResponseInternalRoutesMember1.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseInternalRoutesMember2 != null)
                {
                    return ProjectsPostResponseInternalRoutesMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ProjectsPostResponseInternalRoutesMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember1>(null, ProjectsPostResponseInternalRoutesMember1);
                }
                else if(ProjectsPostResponseInternalRoutesMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_internalRoutesMember2>(null, ProjectsPostResponseInternalRoutesMember2);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsPostResponse_link : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1? ProjectsPostResponseLinkMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1 ProjectsPostResponseLinkMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2? ProjectsPostResponseLinkMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2 ProjectsPostResponseLinkMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3? ProjectsPostResponseLinkMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3 ProjectsPostResponseLinkMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4? ProjectsPostResponseLinkMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4 ProjectsPostResponseLinkMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5? ProjectsPostResponseLinkMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5 ProjectsPostResponseLinkMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6? ProjectsPostResponseLinkMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6 ProjectsPostResponseLinkMember6 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_link();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember1 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember2 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember3 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember4 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember5 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseLinkMember6 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProjectsPostResponseLinkMember1 != null)
                {
                    return ProjectsPostResponseLinkMember1.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseLinkMember2 != null)
                {
                    return ProjectsPostResponseLinkMember2.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseLinkMember3 != null)
                {
                    return ProjectsPostResponseLinkMember3.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseLinkMember4 != null)
                {
                    return ProjectsPostResponseLinkMember4.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseLinkMember5 != null)
                {
                    return ProjectsPostResponseLinkMember5.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseLinkMember6 != null)
                {
                    return ProjectsPostResponseLinkMember6.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ProjectsPostResponseLinkMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember1>(null, ProjectsPostResponseLinkMember1);
                }
                else if(ProjectsPostResponseLinkMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember2>(null, ProjectsPostResponseLinkMember2);
                }
                else if(ProjectsPostResponseLinkMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember3>(null, ProjectsPostResponseLinkMember3);
                }
                else if(ProjectsPostResponseLinkMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember4>(null, ProjectsPostResponseLinkMember4);
                }
                else if(ProjectsPostResponseLinkMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember5>(null, ProjectsPostResponseLinkMember5);
                }
                else if(ProjectsPostResponseLinkMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_linkMember6>(null, ProjectsPostResponseLinkMember6);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsPostResponse_microfrontends : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1? ProjectsPostResponseMicrofrontendsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1 ProjectsPostResponseMicrofrontendsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2? ProjectsPostResponseMicrofrontendsMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2 ProjectsPostResponseMicrofrontendsMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3? ProjectsPostResponseMicrofrontendsMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3 ProjectsPostResponseMicrofrontendsMember3 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_microfrontends();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseMicrofrontendsMember1 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseMicrofrontendsMember2 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseMicrofrontendsMember3 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProjectsPostResponseMicrofrontendsMember1 != null)
                {
                    return ProjectsPostResponseMicrofrontendsMember1.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseMicrofrontendsMember2 != null)
                {
                    return ProjectsPostResponseMicrofrontendsMember2.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseMicrofrontendsMember3 != null)
                {
                    return ProjectsPostResponseMicrofrontendsMember3.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ProjectsPostResponseMicrofrontendsMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember1>(null, ProjectsPostResponseMicrofrontendsMember1);
                }
                else if(ProjectsPostResponseMicrofrontendsMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember2>(null, ProjectsPostResponseMicrofrontendsMember2);
                }
                else if(ProjectsPostResponseMicrofrontendsMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_microfrontendsMember3>(null, ProjectsPostResponseMicrofrontendsMember3);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProjectsPostResponse_trustedIps : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1? ProjectsPostResponseTrustedIpsMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1 ProjectsPostResponseTrustedIpsMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2? ProjectsPostResponseTrustedIpsMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2 ProjectsPostResponseTrustedIpsMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse.ProjectsPostResponse_trustedIps();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseTrustedIpsMember1 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.ProjectsPostResponseTrustedIpsMember2 = new global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(ProjectsPostResponseTrustedIpsMember1 != null)
                {
                    return ProjectsPostResponseTrustedIpsMember1.GetFieldDeserializers();
                }
                else if(ProjectsPostResponseTrustedIpsMember2 != null)
                {
                    return ProjectsPostResponseTrustedIpsMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ProjectsPostResponseTrustedIpsMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember1>(null, ProjectsPostResponseTrustedIpsMember1);
                }
                else if(ProjectsPostResponseTrustedIpsMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V11.Projects.ProjectsPostResponse_trustedIpsMember2>(null, ProjectsPostResponseTrustedIpsMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
