// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithUserGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Timestamp in milliseconds when the user requested access to the team.</summary>
        public double? AccessRequestedAt { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Map of the connected Bitbucket account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_bitbucket? Bitbucket { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_bitbucket Bitbucket { get; set; }
#endif
        /// <summary>Current status of the membership. Will be `true` if confirmed, if pending it&apos;ll be `false`.</summary>
        public bool? Confirmed { get; set; }
        /// <summary>Map of the connected GitHub account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_github? Github { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_github Github { get; set; }
#endif
        /// <summary>Map of the connected GitLab account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_gitlab? Gitlab { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_gitlab Gitlab { get; set; }
#endif
        /// <summary>A map that describes the origin from where the user joined.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_joinedFrom? JoinedFrom { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_joinedFrom JoinedFrom { get; set; }
#endif
        /// <summary>The name of the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamName { get; set; }
#nullable restore
#else
        public string TeamName { get; set; }
#endif
        /// <summary>The slug of the team.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TeamSlug { get; set; }
#nullable restore
#else
        public string TeamSlug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse"/> and sets the default values.
        /// </summary>
        public WithUserGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accessRequestedAt", n => { AccessRequestedAt = n.GetDoubleValue(); } },
                { "bitbucket", n => { Bitbucket = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_bitbucket>(global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_bitbucket.CreateFromDiscriminatorValue); } },
                { "confirmed", n => { Confirmed = n.GetBoolValue(); } },
                { "github", n => { Github = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_github>(global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_github.CreateFromDiscriminatorValue); } },
                { "gitlab", n => { Gitlab = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_gitlab>(global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_gitlab.CreateFromDiscriminatorValue); } },
                { "joinedFrom", n => { JoinedFrom = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_joinedFrom>(global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_joinedFrom.CreateFromDiscriminatorValue); } },
                { "teamName", n => { TeamName = n.GetStringValue(); } },
                { "teamSlug", n => { TeamSlug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("accessRequestedAt", AccessRequestedAt);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_bitbucket>("bitbucket", Bitbucket);
            writer.WriteBoolValue("confirmed", Confirmed);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_github>("github", Github);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_gitlab>("gitlab", Gitlab);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Teams.Item.Request.Item.WithUserGetResponse_joinedFrom>("joinedFrom", JoinedFrom);
            writer.WriteStringValue("teamName", TeamName);
            writer.WriteStringValue("teamSlug", TeamSlug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
