// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ConfigPutRequestBody_crs_sf_action
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "deny")]
        #pragma warning disable CS1591
        Deny,
        #pragma warning restore CS1591
        [EnumMember(Value = "log")]
        #pragma warning disable CS1591
        Log,
        #pragma warning restore CS1591
    }
}
