// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config
{
    /// <summary>
    /// Update log headers configuration
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigPatchRequestBodyMember14 : IParsable
    {
        /// <summary>The action property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value? Value { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value Value { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "value", n => { Value = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value>(global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value>("value", Value);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ConfigPatchRequestBodyMember14_value : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? ConfigPatchRequestBodyMember14ValueString { get; set; }
#nullable restore
#else
            public string ConfigPatchRequestBodyMember14ValueString { get; set; }
#endif
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V1.Security.Firewall.Config.ConfigPatchRequestBodyMember14.ConfigPatchRequestBodyMember14_value();
                if(parseNode.GetStringValue() is string configPatchRequestBodyMember14ValueStringValue)
                {
                    result.ConfigPatchRequestBodyMember14ValueString = configPatchRequestBodyMember14ValueStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(ConfigPatchRequestBodyMember14ValueString != null)
                {
                    writer.WriteStringValue(null, ConfigPatchRequestBodyMember14ValueString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
