// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Vercel.OpenApiClient.Aliases;
using Soenneker.Vercel.OpenApiClient.Projects;
using Soenneker.Vercel.OpenApiClient.V10;
using Soenneker.Vercel.OpenApiClient.V11;
using Soenneker.Vercel.OpenApiClient.V12;
using Soenneker.Vercel.OpenApiClient.V13;
using Soenneker.Vercel.OpenApiClient.V1;
using Soenneker.Vercel.OpenApiClient.V2;
using Soenneker.Vercel.OpenApiClient.V3;
using Soenneker.Vercel.OpenApiClient.V4;
using Soenneker.Vercel.OpenApiClient.V5;
using Soenneker.Vercel.OpenApiClient.V6;
using Soenneker.Vercel.OpenApiClient.V7;
using Soenneker.Vercel.OpenApiClient.V8;
using Soenneker.Vercel.OpenApiClient.V9;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Vercel.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class VercelOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The aliases property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Aliases.AliasesRequestBuilder Aliases
        {
            get => new global::Soenneker.Vercel.OpenApiClient.Aliases.AliasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::Soenneker.Vercel.OpenApiClient.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::Soenneker.Vercel.OpenApiClient.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v1 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V1.V1RequestBuilder V1
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V1.V1RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v10 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V10.V10RequestBuilder V10
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V10.V10RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v11 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V11.V11RequestBuilder V11
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V11.V11RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v12 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V12.V12RequestBuilder V12
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V12.V12RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v13 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V13.V13RequestBuilder V13
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V13.V13RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v2 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V2.V2RequestBuilder V2
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V2.V2RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v3 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V3.V3RequestBuilder V3
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V3.V3RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v4 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V4.V4RequestBuilder V4
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V4.V4RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v5 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V5.V5RequestBuilder V5
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V5.V5RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v6 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V6.V6RequestBuilder V6
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V6.V6RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v7 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V7.V7RequestBuilder V7
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V7.V7RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v8 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V8.V8RequestBuilder V8
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V8.V8RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The v9 property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V9.V9RequestBuilder V9
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V9.V9RequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.VercelOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public VercelOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.vercel.com";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
