// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V10.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ProjectsGetResponseMember3_projects_env_contentHintMember6_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "blob-store-id")]
        #pragma warning disable CS1591
        BlobStoreId,
        #pragma warning restore CS1591
    }
}
