// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithResourceGetResponse_protocolSettings_experimentation : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The edgeConfigId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EdgeConfigId { get; set; }
#nullable restore
#else
        public string EdgeConfigId { get; set; }
#endif
        /// <summary>The edgeConfigSyncingEnabled property</summary>
        public bool? EdgeConfigSyncingEnabled { get; set; }
        /// <summary>The edgeConfigTokenId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EdgeConfigTokenId { get; set; }
#nullable restore
#else
        public string EdgeConfigTokenId { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item.WithResourceGetResponse_protocolSettings_experimentation"/> and sets the default values.
        /// </summary>
        public WithResourceGetResponse_protocolSettings_experimentation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item.WithResourceGetResponse_protocolSettings_experimentation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item.WithResourceGetResponse_protocolSettings_experimentation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item.WithResourceGetResponse_protocolSettings_experimentation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "edgeConfigId", n => { EdgeConfigId = n.GetStringValue(); } },
                { "edgeConfigSyncingEnabled", n => { EdgeConfigSyncingEnabled = n.GetBoolValue(); } },
                { "edgeConfigTokenId", n => { EdgeConfigTokenId = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("edgeConfigId", EdgeConfigId);
            writer.WriteBoolValue("edgeConfigSyncingEnabled", EdgeConfigSyncingEnabled);
            writer.WriteStringValue("edgeConfigTokenId", EdgeConfigTokenId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
