// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Resources.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WithResourcePatchRequestBody_billingPlan_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "prepayment")]
        #pragma warning disable CS1591
        Prepayment,
        #pragma warning restore CS1591
        [EnumMember(Value = "subscription")]
        #pragma warning disable CS1591
        Subscription,
        #pragma warning restore CS1591
    }
}
