// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item.Secrets;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\installations\{integrationConfigurationId}\products\{integrationProductIdOrSlug}\resources\{resourceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithResourceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The secrets property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item.Secrets.SecretsRequestBuilder Secrets
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item.Secrets.SecretsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/installations/{integrationConfigurationId}/products/{integrationProductIdOrSlug}/resources/{resourceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Installations.Item.Products.Item.Resources.Item.WithResourceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithResourceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/installations/{integrationConfigurationId}/products/{integrationProductIdOrSlug}/resources/{resourceId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
