// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V2.Sandboxes
{
    /// <summary>Field to sort by.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSortByQueryParameterType
    {
        [EnumMember(Value = "createdAt")]
        #pragma warning disable CS1591
        CreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "name")]
        #pragma warning disable CS1591
        Name,
        #pragma warning restore CS1591
        [EnumMember(Value = "statusUpdatedAt")]
        #pragma warning disable CS1591
        StatusUpdatedAt,
        #pragma warning restore CS1591
    }
}
