// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Projects.Item.Routes
{
    /// <summary>
    /// A version of routing rules stored in S3.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RoutesPutResponse_version : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The staging alias for previewing this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The user who created this version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>Unique identifier for the version.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether this version is currently live in production.</summary>
        public bool? IsLive { get; set; }
        /// <summary>Whether this version is staged and not yet promoted to production.</summary>
        public bool? IsStaging { get; set; }
        /// <summary>Timestamp of when this version was last modified.</summary>
        public double? LastModified { get; set; }
        /// <summary>The number of routing rules in this version.</summary>
        public double? RuleCount { get; set; }
        /// <summary>The S3 key where the routing rules are stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? S3Key { get; set; }
#nullable restore
#else
        public string S3Key { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.Routes.RoutesPutResponse_version"/> and sets the default values.
        /// </summary>
        public RoutesPutResponse_version()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.Routes.RoutesPutResponse_version"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.Routes.RoutesPutResponse_version CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.Routes.RoutesPutResponse_version();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "isLive", n => { IsLive = n.GetBoolValue(); } },
                { "isStaging", n => { IsStaging = n.GetBoolValue(); } },
                { "lastModified", n => { LastModified = n.GetDoubleValue(); } },
                { "ruleCount", n => { RuleCount = n.GetDoubleValue(); } },
                { "s3Key", n => { S3Key = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("isLive", IsLive);
            writer.WriteBoolValue("isStaging", IsStaging);
            writer.WriteDoubleValue("lastModified", LastModified);
            writer.WriteDoubleValue("ruleCount", RuleCount);
            writer.WriteStringValue("s3Key", S3Key);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
