// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V10.Projects.Item.Env
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnvPostResponse_createdMember1_internalContentHint_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "flags-secret")]
        #pragma warning disable CS1591
        FlagsSecret,
        #pragma warning restore CS1591
    }
}
