// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item.Plans;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\integrations\integration\{integrationIdOrSlug}\products\{productIdOrSlug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProductIdOrSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The plans property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item.Plans.PlansRequestBuilder Plans
        {
            get => new global::Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item.Plans.PlansRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item.WithProductIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductIdOrSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/integrations/integration/{integrationIdOrSlug}/products/{productIdOrSlug}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Integrations.Integration.Item.Products.Item.WithProductIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProductIdOrSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/integrations/integration/{integrationIdOrSlug}/products/{productIdOrSlug}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
