// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V2.Domains.Item.Records
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecordsPostRequestBodyMember7_srv : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The port property</summary>
        public double? Port { get; set; }
        /// <summary>The priority property</summary>
        public double? Priority { get; set; }
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Target { get; set; }
#nullable restore
#else
        public string Target { get; set; }
#endif
        /// <summary>The weight property</summary>
        public double? Weight { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V2.Domains.Item.Records.RecordsPostRequestBodyMember7_srv"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V2.Domains.Item.Records.RecordsPostRequestBodyMember7_srv CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V2.Domains.Item.Records.RecordsPostRequestBodyMember7_srv();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "port", n => { Port = n.GetDoubleValue(); } },
                { "priority", n => { Priority = n.GetDoubleValue(); } },
                { "target", n => { Target = n.GetStringValue(); } },
                { "weight", n => { Weight = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("port", Port);
            writer.WriteDoubleValue("priority", Priority);
            writer.WriteStringValue("target", Target);
            writer.WriteDoubleValue("weight", Weight);
        }
    }
}
#pragma warning restore CS0618
