// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Vercel.OpenApiClient.V9.Projects.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithIdOrNamePatchResponse_env : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The configurationId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConfigurationId { get; set; }
#nullable restore
#else
        public string ConfigurationId { get; set; }
#endif
        /// <summary>The contentHint property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint? ContentHint { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint ContentHint { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public double? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The customEnvironmentIds property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomEnvironmentIds { get; set; }
#nullable restore
#else
        public List<string> CustomEnvironmentIds { get; set; }
#endif
        /// <summary>The decrypted property</summary>
        public bool? Decrypted { get; set; }
        /// <summary>The edgeConfigId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EdgeConfigId { get; set; }
#nullable restore
#else
        public string EdgeConfigId { get; set; }
#endif
        /// <summary>The edgeConfigTokenId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EdgeConfigTokenId { get; set; }
#nullable restore
#else
        public string EdgeConfigTokenId { get; set; }
#endif
        /// <summary>The gitBranch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GitBranch { get; set; }
#nullable restore
#else
        public string GitBranch { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Similar to `contentHints`, but should not be exposed to the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_internalContentHint? InternalContentHint { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_internalContentHint InternalContentHint { get; set; }
#endif
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>Legacy now-encryption ciphertext, present after migration swaps value/vsmValue</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegacyValue { get; set; }
#nullable restore
#else
        public string LegacyValue { get; set; }
#endif
        /// <summary>This is used to identify variables that have been migrated from type secret to sensitive.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SunsetSecretId { get; set; }
#nullable restore
#else
        public string SunsetSecretId { get; set; }
#endif
        /// <summary>The target property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target? Target { get; set; }
#nullable restore
#else
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target Target { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_type? Type { get; set; }
        /// <summary>The updatedAt property</summary>
        public double? UpdatedAt { get; set; }
        /// <summary>The updatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The value property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>The vsmValue property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VsmValue { get; set; }
#nullable restore
#else
        public string VsmValue { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env"/> and sets the default values.
        /// </summary>
        public WithIdOrNamePatchResponse_env()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "configurationId", n => { ConfigurationId = n.GetStringValue(); } },
                { "contentHint", n => { ContentHint = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint>(global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint.CreateFromDiscriminatorValue); } },
                { "createdAt", n => { CreatedAt = n.GetDoubleValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "customEnvironmentIds", n => { CustomEnvironmentIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "decrypted", n => { Decrypted = n.GetBoolValue(); } },
                { "edgeConfigId", n => { EdgeConfigId = n.GetStringValue(); } },
                { "edgeConfigTokenId", n => { EdgeConfigTokenId = n.GetStringValue(); } },
                { "gitBranch", n => { GitBranch = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "internalContentHint", n => { InternalContentHint = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_internalContentHint>(global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_internalContentHint.CreateFromDiscriminatorValue); } },
                { "key", n => { Key = n.GetStringValue(); } },
                { "legacyValue", n => { LegacyValue = n.GetStringValue(); } },
                { "sunsetSecretId", n => { SunsetSecretId = n.GetStringValue(); } },
                { "target", n => { Target = n.GetObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target>(global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_type>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDoubleValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetStringValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
                { "vsmValue", n => { VsmValue = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("configurationId", ConfigurationId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint>("contentHint", ContentHint);
            writer.WriteDoubleValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteCollectionOfPrimitiveValues<string>("customEnvironmentIds", CustomEnvironmentIds);
            writer.WriteBoolValue("decrypted", Decrypted);
            writer.WriteStringValue("edgeConfigId", EdgeConfigId);
            writer.WriteStringValue("edgeConfigTokenId", EdgeConfigTokenId);
            writer.WriteStringValue("gitBranch", GitBranch);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_internalContentHint>("internalContentHint", InternalContentHint);
            writer.WriteStringValue("key", Key);
            writer.WriteStringValue("legacyValue", LegacyValue);
            writer.WriteStringValue("sunsetSecretId", SunsetSecretId);
            writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target>("target", Target);
            writer.WriteEnumValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_type>("type", Type);
            writer.WriteDoubleValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("updatedBy", UpdatedBy);
            writer.WriteStringValue("value", Value);
            writer.WriteStringValue("vsmValue", VsmValue);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithIdOrNamePatchResponse_env_contentHint : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1? WithIdOrNamePatchResponseEnvContentHintMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1 WithIdOrNamePatchResponseEnvContentHintMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10? WithIdOrNamePatchResponseEnvContentHintMember10 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10 WithIdOrNamePatchResponseEnvContentHintMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11? WithIdOrNamePatchResponseEnvContentHintMember11 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11 WithIdOrNamePatchResponseEnvContentHintMember11 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12? WithIdOrNamePatchResponseEnvContentHintMember12 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12 WithIdOrNamePatchResponseEnvContentHintMember12 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13? WithIdOrNamePatchResponseEnvContentHintMember13 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13 WithIdOrNamePatchResponseEnvContentHintMember13 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14? WithIdOrNamePatchResponseEnvContentHintMember14 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14 WithIdOrNamePatchResponseEnvContentHintMember14 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15? WithIdOrNamePatchResponseEnvContentHintMember15 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15 WithIdOrNamePatchResponseEnvContentHintMember15 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16? WithIdOrNamePatchResponseEnvContentHintMember16 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16 WithIdOrNamePatchResponseEnvContentHintMember16 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2? WithIdOrNamePatchResponseEnvContentHintMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2 WithIdOrNamePatchResponseEnvContentHintMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3? WithIdOrNamePatchResponseEnvContentHintMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3 WithIdOrNamePatchResponseEnvContentHintMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4? WithIdOrNamePatchResponseEnvContentHintMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4 WithIdOrNamePatchResponseEnvContentHintMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5? WithIdOrNamePatchResponseEnvContentHintMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5 WithIdOrNamePatchResponseEnvContentHintMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6? WithIdOrNamePatchResponseEnvContentHintMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6 WithIdOrNamePatchResponseEnvContentHintMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7? WithIdOrNamePatchResponseEnvContentHintMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7 WithIdOrNamePatchResponseEnvContentHintMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8? WithIdOrNamePatchResponseEnvContentHintMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8 WithIdOrNamePatchResponseEnvContentHintMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9? WithIdOrNamePatchResponseEnvContentHintMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9 WithIdOrNamePatchResponseEnvContentHintMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_contentHint();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember1 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember10 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember11 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember12 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember13 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember14 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember15 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember16 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember2 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember3 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember4 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember5 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember6 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember7 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember8 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithIdOrNamePatchResponseEnvContentHintMember9 = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WithIdOrNamePatchResponseEnvContentHintMember1 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember1.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember10 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember10.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember11 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember11.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember12 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember12.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember13 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember13.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember14 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember14.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember15 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember15.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember16 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember16.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember2 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember2.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember3 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember3.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember4 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember4.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember5 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember5.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember6 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember6.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember7 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember7.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember8 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember8.GetFieldDeserializers();
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember9 != null)
                {
                    return WithIdOrNamePatchResponseEnvContentHintMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithIdOrNamePatchResponseEnvContentHintMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember1>(null, WithIdOrNamePatchResponseEnvContentHintMember1);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember10 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember10>(null, WithIdOrNamePatchResponseEnvContentHintMember10);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember11 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember11>(null, WithIdOrNamePatchResponseEnvContentHintMember11);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember12 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember12>(null, WithIdOrNamePatchResponseEnvContentHintMember12);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember13 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember13>(null, WithIdOrNamePatchResponseEnvContentHintMember13);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember14 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember14>(null, WithIdOrNamePatchResponseEnvContentHintMember14);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember15 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember15>(null, WithIdOrNamePatchResponseEnvContentHintMember15);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember16 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember16>(null, WithIdOrNamePatchResponseEnvContentHintMember16);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember2>(null, WithIdOrNamePatchResponseEnvContentHintMember2);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember3>(null, WithIdOrNamePatchResponseEnvContentHintMember3);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember4>(null, WithIdOrNamePatchResponseEnvContentHintMember4);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember5>(null, WithIdOrNamePatchResponseEnvContentHintMember5);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember6>(null, WithIdOrNamePatchResponseEnvContentHintMember6);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember7>(null, WithIdOrNamePatchResponseEnvContentHintMember7);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember8>(null, WithIdOrNamePatchResponseEnvContentHintMember8);
                }
                else if(WithIdOrNamePatchResponseEnvContentHintMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env_contentHintMember9>(null, WithIdOrNamePatchResponseEnvContentHintMember9);
                }
            }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="string"/>, List&lt;string&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithIdOrNamePatchResponse_env_target : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type List&lt;string&gt;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public List<string>? String { get; set; }
#nullable restore
#else
            public List<string> String { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public string? WithIdOrNamePatchResponseEnvTargetString { get; set; }
#nullable restore
#else
            public string WithIdOrNamePatchResponseEnvTargetString { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V9.Projects.Item.WithIdOrNamePatchResponse_env.WithIdOrNamePatchResponse_env_target();
                if(parseNode.GetStringValue() is string withIdOrNamePatchResponseEnvTargetStringValue)
                {
                    result.WithIdOrNamePatchResponseEnvTargetString = withIdOrNamePatchResponseEnvTargetStringValue;
                }
                else if(parseNode.GetCollectionOfPrimitiveValues<string>()?.AsList() is List<string> stringValue)
                {
                    result.String = stringValue;
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(WithIdOrNamePatchResponseEnvTargetString != null)
                {
                    writer.WriteStringValue(null, WithIdOrNamePatchResponseEnvTargetString);
                }
                else if(String != null)
                {
                    writer.WriteCollectionOfPrimitiveValues<string>(null, String);
                }
            }
        }
    }
}
#pragma warning restore CS0618
