// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SegmentsPutResponse_data_rules_conditions_lhsMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "entity")]
        #pragma warning disable CS1591
        Entity,
        #pragma warning restore CS1591
    }
}
