// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Env
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EnvPostRequestBody_target
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "production")]
        #pragma warning disable CS1591
        Production,
        #pragma warning restore CS1591
        [EnumMember(Value = "preview")]
        #pragma warning disable CS1591
        Preview,
        #pragma warning restore CS1591
        [EnumMember(Value = "development")]
        #pragma warning disable CS1591
        Development,
        #pragma warning restore CS1591
    }
}
