// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V2.Teams.Item.Members
{
    /// <summary>Sets the project roles for the invited user</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Members_projects_role
    {
        [EnumMember(Value = "ADMIN")]
        #pragma warning disable CS1591
        ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_VIEWER")]
        #pragma warning disable CS1591
        PROJECT_VIEWER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_DEVELOPER")]
        #pragma warning disable CS1591
        PROJECT_DEVELOPER,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROJECT_GUEST")]
        #pragma warning disable CS1591
        PROJECT_GUEST,
        #pragma warning restore CS1591
    }
}
