// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V6.Deployments
{
    /// <summary>Whether the value is an opaque identifier or a URL.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DeploymentsGetResponse_deployments_platform_origin_type
    {
        [EnumMember(Value = "url")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
        [EnumMember(Value = "id")]
        #pragma warning disable CS1591
        Id,
        #pragma warning restore CS1591
    }
}
