// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\env\{id}\unlink\{projectId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithProjectItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/env/{id}/unlink/{projectId}{?slug*,teamId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithProjectItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/env/{id}/unlink/{projectId}{?slug*,teamId*}", rawUrl)
        {
        }
        /// <summary>
        /// Disconnects a shared environment variable for a given project
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectPatchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectPatchResponse?> PatchAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder.WithProjectItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectPatchResponse> PatchAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder.WithProjectItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToPatchRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectPatchResponse>(requestInfo, global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectPatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Disconnects a shared environment variable for a given project
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder.WithProjectItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder.WithProjectItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Vercel.OpenApiClient.V1.Env.Item.Unlink.Item.WithProjectItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Disconnects a shared environment variable for a given project
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithProjectItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>The Team slug to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
            /// <summary>The Team identifier to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("teamId")]
            public string? TeamId { get; set; }
#nullable restore
#else
            [QueryParameter("teamId")]
            public string TeamId { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
