// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\edge-config\{edgeConfigId}\item
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Item_EscapedRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Vercel.OpenApiClient.v1.edgeConfig.item.Item_Escaped.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item.WithEdgeConfigItemKeyItemRequestBuilder"/></returns>
        public global::Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item.WithEdgeConfigItemKeyItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("edgeConfigItemKey", position);
                return new global::Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item.WithEdgeConfigItemKeyItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item_EscapedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Item_EscapedRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/edge-config/{edgeConfigId}/item", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.EdgeConfig.Item.Item_Escaped.Item_EscapedRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Item_EscapedRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/edge-config/{edgeConfigId}/item", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
