// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Vercel.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\projects\{idOrName-id}\feature-flags\segments\{segmentIdOrSlug}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithSegmentIdOrSlugItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSegmentIdOrSlugItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{idOrName%2Did}/feature-flags/segments/{segmentIdOrSlug}{?slug*,teamId*,withMetadata*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithSegmentIdOrSlugItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/projects/{idOrName%2Did}/feature-flags/segments/{segmentIdOrSlug}{?slug*,teamId*,withMetadata*}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a feature flag segment.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve a feature flag segment by ID or slug.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.Models.Segment"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Vercel.OpenApiClient.Models.Segment?> GetAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Vercel.OpenApiClient.Models.Segment> GetAsync(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Vercel.OpenApiClient.Models.Segment>(requestInfo, global::Soenneker.Vercel.OpenApiClient.Models.Segment.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update an existing feature flag segment.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse?> PatchAsync(global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse> PatchAsync(global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderPatchQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse>(requestInfo, global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a feature flag segment.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderDeleteQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderDeleteQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Retrieve a feature flag segment by ID or slug.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update an existing feature flag segment.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderPatchQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchRequestBody body, Action<RequestConfiguration<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugItemRequestBuilderPatchQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Delete a feature flag segment.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSegmentIdOrSlugItemRequestBuilderDeleteQueryParameters 
        {
            /// <summary>The Team slug to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
            /// <summary>The Team identifier to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("teamId")]
            public string? TeamId { get; set; }
#nullable restore
#else
            [QueryParameter("teamId")]
            public string TeamId { get; set; }
#endif
            /// <summary>Whether to include metadata</summary>
            [QueryParameter("withMetadata")]
            public bool? WithMetadata { get; set; }
        }
        /// <summary>
        /// Retrieve a feature flag segment by ID or slug.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSegmentIdOrSlugItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The Team slug to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
            /// <summary>The Team identifier to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("teamId")]
            public string? TeamId { get; set; }
#nullable restore
#else
            [QueryParameter("teamId")]
            public string TeamId { get; set; }
#endif
            /// <summary>Whether to include metadata</summary>
            [QueryParameter("withMetadata")]
            public bool? WithMetadata { get; set; }
        }
        /// <summary>
        /// Update an existing feature flag segment.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSegmentIdOrSlugItemRequestBuilderPatchQueryParameters 
        {
            /// <summary>The Team slug to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string Slug { get; set; }
#endif
            /// <summary>The Team identifier to perform the request on behalf of.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("teamId")]
            public string? TeamId { get; set; }
#nullable restore
#else
            [QueryParameter("teamId")]
            public string TeamId { get; set; }
#endif
            /// <summary>Whether to include metadata</summary>
            [QueryParameter("withMetadata")]
            public bool? WithMetadata { get; set; }
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Vercel.OpenApiClient.Models.Segment"/>, <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithSegmentIdOrSlugPatchResponse : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.Models.Segment"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.Models.Segment? Segment { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.Models.Segment Segment { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1? WithSegmentIdOrSlugPatchResponseMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1 WithSegmentIdOrSlugPatchResponseMember1 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugItemRequestBuilder.WithSegmentIdOrSlugPatchResponse();
                if("Segment".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.Segment = new global::Soenneker.Vercel.OpenApiClient.Models.Segment();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WithSegmentIdOrSlugPatchResponseMember1 = new global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(Segment != null)
                {
                    return Segment.GetFieldDeserializers();
                }
                else if(WithSegmentIdOrSlugPatchResponseMember1 != null)
                {
                    return WithSegmentIdOrSlugPatchResponseMember1.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(Segment != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.Models.Segment>(null, Segment);
                }
                else if(WithSegmentIdOrSlugPatchResponseMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item.WithSegmentIdOrSlugPatchResponseMember1>(null, WithSegmentIdOrSlugPatchResponseMember1);
                }
            }
        }
    }
}
#pragma warning restore CS0618
