// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Vercel.OpenApiClient.V1.Projects.Item.FeatureFlags.Segments.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum WithSegmentIdOrSlugPatchRequestBody_operations_field
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "include")]
        #pragma warning disable CS1591
        Include,
        #pragma warning restore CS1591
        [EnumMember(Value = "exclude")]
        #pragma warning disable CS1591
        Exclude,
        #pragma warning restore CS1591
    }
}
